### ISSUE TITLE
Can't use mt_rand() in switch

### ISSUE THREAD

**Issue by SliceOfLife** [phalcon/zephir#1001]
We can't use function **mt_rand**, but can use **rand**. Why?

```zep
		switch mt_rand(1, 2) {
			case 1:
				echo "one";
				break;

			case 2:
				echo "two";
				break;
		}
```
On this code compiler we got 
```
Zephir\CompilerException: Unknown expression: long in .../Test.zep on line 18
```
but code below is OK
```zep
		switch rand(1, 2) {
			case 1:
				echo "one";
				break;

			case 2:
				echo "two";
				break;
		}
```
Zephir version 0.7.0a [c6fe91a]

**Comment by steffengy** [comment]
Probably because mt_rand has an optimizer and rand doesn't.
Seems like that's why something goes wrong there, even if it shouldnt
