### ISSUE TITLE
Debuging

### ISSUE THREAD

**Issue by mattvb91** [phalcon/zephir#1007]
Hi everyone,

Recently started getting more and more interested in Zephir/Phalcon. Could someone give me an overview of what the development process is like in terms of debugging the Zephir code?

Is there something similar to Xdebug when I am making changes to the CPhalcon zephir code? How do you usually debug? Compile/Dump output?

**Comment by SliceOfLife** [comment]
Nohow. Compile, run, see the exception. Meditate.

**Comment by mattvb91** [comment]
wow! So for example if you are trying to trace certain values getting passed around the code what is your method of doing that?

**Comment by SliceOfLife** [comment]
All my project in my mind :) Meditation is really works for me.

**Comment by steffengy** [comment]
using some var_dumps for simple cases is sufficient and fairly effective.
the easy bugs are also easy to spot when you just look at the code/function flow.

For heavy cases, where zephir bugs are in play, you can spot a fair amount by
just looking at the generated code or using a dedicated C Debugger.

**Comment by mattvb91** [comment]
Thanks for the input guys. Will take a bit of getting used to compile/run/see exception but I think ill manage.
