### ISSUE TITLE
Constant as other const

### ISSUE THREAD

**Issue by mruz** [phalcon/zephir#1011]
> Zephir\CompilerException: Type "static-constant-access" is not supported.

```zep
class Version
{

    const DEV = 0;
    const ALPHA = 1;
    const BETA = 2;
    const RC = 3;
    const STABLE = 4;

    const MAJOR = 1;
    const MINOR = 0;
    const PATCH = 13;
    const STAGE = self::STABLE;
    const BUILD = 1;
    
    public static function getStage() {
        return self::STAGE;
    }
}
```
```php
echo Version::getStage(); //4
```

**Comment by mruz** [comment]
Also it could be nice to can acces to const by static https://github.com/phalcon/cphalcon/pull/10515
```zep
class A
{
    const VERSION = 1;
    
    public static function getVersion()
    {
        return static::VERSION;
    }
}

class B extends A
{
    const VERSION = 2;
}
```
```php
var_dump(B::getVersion()); //2
```

@ogarbe is this related to https://github.com/phalcon/zephir/issues/513?

**Comment by hylent** [comment]
:+1:

**Comment by ovr** [comment]
Seems to be fixed

**Comment by mruz** [comment]
```zep
class Version
{

    const DEV = 0;
    const ALPHA = 1;
    const BETA = 2;
    const RC = 3;
    const STABLE = 4;

    const MAJOR = 1;
    const MINOR = 0;
    const PATCH = 14;
    const STAGE = self::STABLE;
    const BUILD = 1;
```

> Exception: Cannot resolve constant

If I replace by class name:
```zep
    const STAGE = Version::STABLE;
```
> PHP Warning:  require(/home/mruz/Dropbox/git/ice/framework/vendor/phalcon/zephir/LibraryVersion.php): failed to open stream: No such file or directory in /home/mruz/Dropbox/git/ice/framework/vendor/phalcon/zephir/Library/Loader.php on line 48
PHP Fatal error:  require(): Failed opening required '/home/mruz/Dropbox/git/ice/framework/vendor/phalcon/zephir/LibraryVersion.php' (include_path='.:/usr/share/php5:/usr/share/php5/PEAR') in /home/mruz/Dropbox/git/ice/framework/vendor/phalcon/zephir/Library/Loader.php on line 48

**Comment by ovr** [comment]
> Exception: Cannot resolve constant


@mruz 
It's not possible to get this error, Did you update Zephir to latest master?


I tested 

```zep
//works
const STAGE = self::STABLE;
//works
const STAGE = Version::STABLE;
```

Attention: ice/framework builds is not working correctly
https://travis-ci.org/ice/framework/jobs/68460844#L411

**Comment by mruz** [comment]
After updating version works, thanks ;)
How about second part, access to const by `static::`?
```zep
class Version
{
    const BUILD = 1;

    public static function getBuild() {
        return static::BUILD;
    }
}
```

```php
<?php

class MyVersion extends Version
{
    const BUILD = 2;
}
```

```php
var_dump(MyVersion::getBuild()); //2
```
