### ISSUE TITLE
Is there anyway to custom the entries of extension? 

### ISSUE THREAD

**Issue by kinosang** [phalcon/zephir#1012]
I want to custom something in `PHP_MINIT_FUNCTION` but I didn't find any API for it.
I have to change the compiled .c file manually each time I run `zephir compile`

**Comment by dreamsxin** [comment]
See https://github.com/phalcon/zephir/blob/master/templates/project.c

**Comment by kinosang** [comment]
@dreamsxin  got it. thx.
