### ISSUE TITLE
Syntax error in class name with uppercase

### ISSUE THREAD

**Issue by KorsaR-ZN** [phalcon/zephir#1021]
When you attempt to create the name of the class in uppercase produces a syntax error

**ip.zep**
```
class IP 
{
 ....
}
```

**output**
```
Zephir\ParseException: Syntax error in ...\ip.zep on line N
        class IP
        -------^
```

**Comment by andresgutierrez** [comment]
Identifiers in uppercase are reserved for constants, you have to use: Ip

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Thanks!
I did so when transfer class from the incubator to core, see https://github.com/phalcon/cphalcon/pull/10572
