### ISSUE TITLE
Allow no namespace usage

### ISSUE THREAD

**Issue by munggruel** [phalcon/zephir#1022]
for example：
nonamespace;

my zephir code
....

**Comment by munggruel** [comment]
The reason：
1.the default namespace ‘’ has better performance
2.Reduce the complexity of use 

You must be declared in each file : use  XXXX\XXXX\Class;
Util(keep it simple and stupid)  versus XXXX\XXX\XXX\Util (Too complicated)

**Comment by andresgutierrez** [comment]
Could you please elaborate why the default namespace ‘’ has better performance ?

**Comment by munggruel** [comment]
namespace ns{
    function aa()
    {
    }
}
namespace{
    function getMsecTime()
    {
        $arr = explode( ' ', microtime() );
        return $arr[0] + $arr[1];
    }
    function aa()
    {
    }
    $start = getMsecTime();
    for ($i = 0; $i < 100000; $i++) {
       aa();
    }
    echo "Running Time:", getMsecTime() - $start, "\n";
    //Running Time:0.28701591491699

    $start = getMsecTime();
    for ($i = 0; $i < 100000; $i++) {
        ns\aa();
    }
    echo "Running Time:", getMsecTime() - $start, "\n";
    //Running Time:0.3240180015564
}

**Comment by munggruel** [comment]
Now I write my php framework, I use AOP implement plugin 
plugin use  XXXX\XXXX\Util  too complicated

so I have to use :
class Util extends XXXX\XXXX\Util {}

**Comment by andresgutierrez** [comment]
I execute your script and I get:

```
Running Time:0.022134065628052 // aa()
Running Time:0.009253978729248 // ns\aa()
```

In my case, ns\aa() is 4.5x faster than aa() according to your example

**Comment by munggruel** [comment]
Yes，Zend Optimizer enable 
But how can I 
use XXX\XXX\Util; as Global

**Comment by munggruel** [comment]
for example, I have a file 
_part_footer.tpl
<div class="footer" id="footer">

</div>

hook fille friendly_link.tpl:
{{if isset($LinksList) && XXXX\XXXX\Utils::getClient() == ''}}
	<p class="link">
....
{{/if}}

XXXX\XXXX\Utils::getClient() too long to  remember for someone who want to develop a plugin

**Comment by munggruel** [comment]
_part_footer.tpl:
\<!--{hook plugin/friendly_link/friendly_link.tpl}--\>

**Comment by fezfez** [comment]
:-1:

**Comment by munggruel** [comment]
class_alias can do it
