### ISSUE TITLE
Phalcon\Cache\Backend\memcache的flush方法都存在删除不掉的情况

### ISSUE THREAD

**Issue by gufei** [phalcon/zephir#1023]
原因是在statsKey的在存储中用的是key来存的，但在flush方法中
for key in keys这样的写法key其实取的是value，所以下边的delete动作执行是不成功的

修改方法是改为for key, value in keys

建议官方修复

**Comment by andresgutierrez** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/10612
