### ISSUE TITLE
Bugs with Local Symbol Table and require statement

### ISSUE THREAD

**Issue by guweigang** [phalcon/zephir#1024]
Like the picture said:
<img width="857" alt="1___usr_local_opt_emacs_bin_emacs___users_guweigang_tmp_utils__emacs_" src="https://cloud.githubusercontent.com/assets/178500/8564356/a745534a-257d-11e5-86f3-d21eca770adf.png">

I want to make an variable in zephir which can be accessed in php user-land. You can see it from frame 3.

When i call it in global scope, everything goes right, but when call it in a function, it raises PHP NOTICE: "Undefined variable: foo". You can see it from frame 1.

**Comment by hylent** [comment]
`extract(["foo": this->foo]);`

**Comment by guweigang** [comment]
@hylent that works,,,  but what is the problem with ```let {"foo"}="foo"```  ?

**Comment by andresgutierrez** [comment]
@guweigang Foo is created in the current scope where the variable is created, in the case of test():

```php
function test()
{
  $util = new Util\Greeting();
  $util->say();
  echo $foo;
}

**Comment by guweigang** [comment]
@andresgutierrez You mean ```let {"foo"}="foo";``` create variable in the top scope ?

**Comment by andresgutierrez** [comment]
@guweigang it creates variable in the scope where the function say() was created
