### ISSUE TITLE
zephir_camelize is coping last character as-is

### ISSUE THREAD

**Issue by olivier-monaco** [phalcon/zephir#1032]
See phalcon/cphalcon#10640

From https://github.com/phalcon/cphalcon/blob/master/phalcon/dispatcher.zep#L632

```zephir
let camelizedClass = camelize(handlerName);
handlerName = CONTROLLER
camelizedClass = ControlleR
```

camelize function is replaced be C function named zephir_camelize. Problem comes from https://github.com/phalcon/zephir/blob/master/kernels/ZendEngine2/string.c#L288:

```php
    if (likely(i == len - 1)) {
        smart_str_appendc(&camelize_str, *marker);
    }
```
Last character is copied as-is. It must be "lowercased".

**Comment by andresgutierrez** [comment]
Fixed in master
