### ISSUE TITLE
CompilerException: Class does not have a property

### ISSUE THREAD

**Issue by mruz** [phalcon/zephir#1033]
With the latest changes I'm receiving exception:

> mruz@linux-9cy2:~/Dropbox/git/ice/framework> ./vendor/bin/zephir build
Zephir\CompilerException: Class 'Ice\Config' does not have a property called: 'messages'

It doesn't has, but previously worked, and I don't know where the problem is.

**Comment by mruz** [comment]
I see it happens after https://github.com/phalcon/zephir/commit/e50499b5d8c872526b4dc0615b6d27a08780154b

**Comment by andresgutierrez** [comment]
Does Ice\Config a property called messages?

**Comment by mruz** [comment]
No. I also don't have a reference to the messages attribute in Config.

**Comment by mruz** [comment]
@ovr @steffengy any idea? Can you try to build the [ice/framework](https://github.com/ice/framework) with the latest zephir?

**Comment by mruz** [comment]
@steffengy this is related to your changes https://github.com/phalcon/zephir/pull/980 @andresgutierrez removed it in https://github.com/phalcon/zephir/commit/e50499b5d8c872526b4dc0615b6d27a08780154b.
I see compiler throw exception about Config property, but the `messages` property is from Ice\Mvc\Model. Maybe not clean access before?

If I add messages to Config, then:

> Zephir\CompilerException: Class 'Ice\Config' does not have a property called: 'rules'

If I add rules, then

> Zephir\CompilerException: Class 'Ice\Config' does not have a property called: 'labels'

...

> Zephir\CompilerException: Class 'Ice\Config' does not have a property called: 'relations'
