### ISSUE TITLE
Possible incorrect C code for double divided by long

### ISSUE THREAD

**Issue by ioncube** [phalcon/zephir#1038]
Hi
I noticed that:

float x = 123.0;
int y = 5;
var z;
let z = x / y;

produces:

z = zephir_safe_div_double_long(x,  (double) y TSRMLS_CC);

Casting y do double here seems incorrect given that the function expects a long for its 2nd arg. 
##

**Comment by joeyhub** [comment]
It's still doing it. It's not possibly incorrect, it *is* incorrect.

See: https://github.com/phalcon/zephir/issues/422
