### ISSUE TITLE
Zephir slow on modifying big array

### ISSUE THREAD

**Issue by thomasbley** [phalcon/zephir#1041]
I have the following code to benchmark zephir:

utils/example.zep
```zep
namespace Utils;

class Example {
public static function run() {
    array array3 = [];
    int i = 0;
    while (i < 1000000) {
        let array3[i] = i*2;
        let i++;
    }
    var start;
    let start = microtime(true);
    int length3;
    let length3 = count(array3);
    let i = 0;
    while (i < length3) {
        let array3[i] += 1;
        let i++;
    }
    echo (microtime(true) - start) . PHP_EOL;
}
}
```

zephir build && php -d extension=utils.so -r 'echo Utils\Example::run();'

php code:
```php
<?php
function test(){
$array = array();
for ($i=0; $i<1000000; $i++) $array[] = $i*2;

$start = microtime(true);
$count = count($array);
for ($key=0; $key<$count; $key++) $array[$key]++;
echo microtime(true)-$start . PHP_EOL;
}
test();
```

Result is almost same as PHP code:
0.1663990020752

c++ is:
0.01149
c++ (-O3) is:
0.00101
hhvm is:
0.05

any ideas to improve my code?

zephir 0.7.1b
php 5.5.9
hhvm 3.8.1

**Comment by andresgutierrez** [comment]
Zephir does not have specialized structured for arrays different than the same structures for arrays provided by PHP so it's likely the same speed. Probably when PHP7 support is available it would improve.

**Comment by steffengy** [comment]
Closed since that is unpreventable with the current array implementation.
