### ISSUE TITLE
str_replace null error BUG

### ISSUE THREAD

**Issue by imadige** [phalcon/zephir#1055]
let str2=str_replace(["aa"],["aaa"],"bla bla aa aaa askks");

str2 null

**Comment by imadige** [comment]
http://php.net/manual/en/function.str-replace.php


<?php
// Provides: <body text='black'>
$bodytag = str_replace("%body%", "black", "<body text='%body%'>");

// Provides: Hll Wrld f PHP
$vowels = array("a", "e", "i", "o", "u", "A", "E", "I", "O", "U");
$onlyconsonants = str_replace($vowels, "", "Hello World of PHP");

// Provides: You should eat pizza, beer, and ice cream every day
$phrase  = "You should eat fruits, vegetables, and fiber every day.";
$healthy = array("fruits", "vegetables", "fiber");
$yummy   = array("pizza", "beer", "ice cream");

$newphrase = str_replace($healthy, $yummy, $phrase);

// Provides: 2
$str = str_replace("ll", "", "good golly miss molly!", $count);
echo $count;
?>

**Comment by sergeyklay** [comment]
Dublicate https://github.com/phalcon/zephir/issues/732

**Comment by lolo32** [comment]
I post a merge request #1059 to solve this problem.

**Comment by steffengy** [comment]
Fixed in development.
