### ISSUE TITLE
Getting the first character of a string with $str[0]

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir#1057]
In PHP strings can be seen as Char Arrays, and the way to access a position of an array is to use the `[ ]` operator, so there's no problem at all in using `$str[0]` (and I'm pretty sure is much faster than the `substr` method).

**php** work fine:

```php
$str = "abc";
echo $str[0]; // a
```

**zephir** need extra work (using `chr`)

```zephir
namespace Test;
class Test
{
	public function test()
	{
		string str;
		let str = "abc";

		return str[0];

	}
}
```

```sh
php -r '$a = new Test; var_dump($a->test());'
int(97)
```

**Comment by andresgutierrez** [comment]
This is the intended usage, as it's an array of chars, it returns a char like in C, it does not return a string like in PHP.

**Comment by sergeyklay** [comment]
Ok. But in PHP I can use something this:
```php
$str = "abc";
$str[0] = 'z';
echo $str; // zbc
```

However in Zephir can't

```zephir
namespace Test;
class Test
{
    public function test()
    {
        string str;
        let str = "abc";
        let str[0] = ord("z");

        return str;
    }
}
```

```
php -r '$a = new Test; var_dump($a->test());'
Warning: Cannot use a scalar value as an array ...

string(3) "abc"
```

**Comment by andresgutierrez** [comment]
Yeah, but Zephir is not PHP

**Comment by sergeyklay** [comment]
In Zephir I can't use something like:
```zephir
let str = "abc";
return ord(str[0]);
```

only 
```zephir
let str = "abc";
ord(substr(bin, 0, 1));
```

**Comment by sergeyklay** [comment]
In any case, thanks for the clarification :)
