### ISSUE TITLE
[NFR] ldexp

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir#1058]
PHP & Zephir does not have `ldexp(x,n)` function from Math library:
http://www.codecogs.com/library/computing/c/math.h/ldexp.php

> The *ldexp* functions multiply x by 2 to the power of n.

**go**
```go
math.Ldexp(2,3) // 16
```
**ruby**
```ruby
Math.ldexp(2,3) # 16.0
```

**python**
```python
math.ldexp(2,3) # 16.0
```

**c**
```c
#include <math.h>
ldexp(2.0,3) // 16.0
```

It may be implemented like that:
```zephit
function ldexp(x, n)
{
   return x * pow(2, n);
}
```

**Comment by ovr** [comment]
Will do it tomorrow

**Comment by sergeyklay** [comment]
:+1:

**Comment by ovr** [comment]
Started, I am working on this problem now
Will create optimizer for Zephir
And NFR for PHP core

**Comment by ovr** [comment]
refs https://github.com/php/php-src/pull/1489

**Comment by sergeyklay** [comment]
any progress?

**Comment by sergeyklay** [comment]
Done
