### ISSUE TITLE
ArrayAccess incorrect behavior

### ISSUE THREAD

**Issue by bubleg** [phalcon/zephir#1061]
Hello there.

It seems that classes that implement SPL ArrayAccess interface do not actually act like arrays in the Zephire code (compiled PHP classes work fine). And moreover they act differently whether the class implementing this interface is a property (doesn't matter if public or private) of another class or just a local variable.

An example of what I'm talking about: https://github.com/bubleg/zephir_bug_arrayaccess

I'm using Vagrant box with **debian/jessie64** with all updates and Zephir version **0.7.1b**

Thanks.
##

**Comment by sergeyklay** [comment]
Closed in favor of https://github.com/phalcon/zephir/issues/1400
