### ISSUE TITLE
[Optimizer] Using a 3rd party library

### ISSUE THREAD

**Issue by treffynnon** [phalcon/zephir#128]
I am trying to use an optimizer to pull in a third party piece of code just as described in [the comments on pull request #21](https://github.com/phalcon/zephir/pull/21#issuecomment-26178522). Just to confirm I am not using the CBLOCK syntax that this PR was in relation to, but trying to follow the optimizer example given.

Whenever I try to compile I am getting the following error back:

``` bash
Warning: Function "fibonacci" does not exist at compile time in /path/to/zephir-extension/extname/extname/test.zep on 7 [nonexistent-function]

            fibonacci(arg);
    -----------------------^
```

I have used the same directory structure as the aforementioned ticket and replicated the code. Is there something missing? Is there something more I need to do to get Zephir to look at the header file?

**Comment by ramsey** [comment]
@treffynnon What was your solution for working around the string return values in Zephir optimizers? I think I'm running into the same or a similar issue as you describe here. It's returning the name of the function (i.e. "my_foobar()") rather than running and returning the value of the C function `my_foobar()`.

My optimizer looks like this:

```
class FoobarOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        return new CompiledExpression('string', 'my_foobar()', $expression);
    }
}
```

My ZEP method looks like:

```
    public static function foobar() -> string
    {
        return foobar();
    }
```

In the generated code, I see the following:

```
PHP_METHOD(Myext_Foobar, foobar) {
	RETURN_STRING("my_foobar()", 1);
}
```

I think I'm expecting to see something more like:

```
RETURN_STRING(my_foobar(), 1);
```

**Comment by treffynnon** [comment]
@ramsey I was working on this project at the time https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir

Perhaps a squiz at https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir/tree/master/cli-php-zephir-optimizer might help you. Unfortunately, I cannot remember what I did now although this looks like it might be the commit I fixed it in https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir/commit/ed9848abdda2541946a202681494eb864f2c864f

**Comment by phalcon** [comment]
@ramsey The way you're returning the generated code implies that my_foobar() returns an string.

You may want to see how existing optimisers are implemented in Zephir: 

https://github.com/phalcon/zephir/blob/master/Library/Optimizers/FunctionCall/VarDumpOptimizer.php#L103-L106

**Comment by ramsey** [comment]
Thanks, @phalcon. After looking through the existing optimizers, I was able to get things working by using the codePrinter with code that passes the zval into a custom C function and uses `ZVAL_STRING()` to set the string on the zval. I was going about it wrong, thinking that the compiled expression would turn into some structure like I mentioned above.
