### ISSUE TITLE
Zephir supported string heredoc syntax?

### ISSUE THREAD

**Issue by jockchou** [phalcon/zephir#1313]
like php here:

http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

``` php
const VARIABLE_REGEX = <<<'REGEX'
\{
    \s* ([a-zA-Z_][a-zA-Z0-9_-]*) \s*
    (?:
        : \s* ([^{}]*(?:\{(?-1)\}[^{}]*)*)
    )?
\}
REGEX;
```

I want define VARIABLE_REGEX above, how to write in zephir???
##

**Comment by Izopi4a** [comment]
you cant. I use public static instead

**Comment by yyyc514** [comment]
Is the heretic syntax itself supported though?
