### ISSUE TITLE
[NFR] Add support for creating classes/methods with capitalized names

### ISSUE THREAD

**Issue by tamaranga** [phalcon/zephir#141]
It's impossible to create class:

```
class HTML {
}
```

and method:

```
class Test {
      public function HTML() {}
}
```

Maybe it is not so difficult to allow such capitalized names or describe this limitation in docs. Currently it's just "ParseException: Syntax error", that is not very obvious.
##

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/php-zephir-parser#17
