### ISSUE TITLE
ParseException Syntax error while call static method dynamically

### ISSUE THREAD

**Issue by ikandars** [phalcon/zephir#197]
I've got "Zephir\ParseException: Syntax error" when try to call a static method dynamically.

<pre>
echo self::{"name"}();
-----------^
</pre>

``` php
namespace Test;

class MyClass
{
    public function __construct()
    {
        echo self::{"name"}();
    }

    public static function name()
    {
        return "Jhon";
    }
}
```

I pulled the source from bc91853e3e8a0528481daaf26f1e04b0fab1ab33 commit id
##

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/php-zephir-parser#22
