### ISSUE TITLE
[NFR] Add support for passing variables by reference

### ISSUE THREAD

**Issue by pigochu** [phalcon/zephir#203]
I want to do this

## zephir code ##

```js
class ZephirClass {
    public static function passvar( & a ) {  // this line parse error
        let a["xxx"] = "999999";
   }
}
```

## php code ##

```php
<?php
$a = ["xxx" => "11111"];
ZephirClass::passvar( $a );
echo $a["xxx"]; // output 99999 
```

is there a way to do this ?

**Comment by zeran86** [comment]
Almost year ...
Is any progress by this ticket? Please, give us a hope )

**Comment by nkt** [comment]
Actually I think this issue is irrelevant due #609.

**Comment by ilei** [comment]
when Support reference parameters?

**Comment by dahweng** [comment]
Hi everyone, I have a simple solution for this problem: use a PHP function for the task of returning a reference.
I have been searching for a solution to this problem for the past couple of days, and managed to get the function that requires references to work by doing the following;

```
<php

// In your PHP

function refValue( $val )
{
    $ref = &$val;
    return $ref;
}

?>
```

After you have created the refValue function in your PHP file, you can then use it in Zephir as follows;

```
// In your Zephir source code
var avar = "passed by value";
var bvar = "passed by reference";

some_function( avar, refValue( bvar ) );
```

I have successfully used this method to get a function that requires references ($mysqli->bind_param()) to work in Zephir.

Goodluck people! HTH

**Comment by sam80180** [comment]
Se puede probar esto：

```php
var $funcVal2Ref = eval("return function &($v) { return $v; };");
array $arr = [];
var $ref = {$funcVal2Ref}($arr);
```
