### ISSUE TITLE
Is any way to use sockets in zephir?

### ISSUE THREAD

**Issue by misterion** [phalcon/zephir#217]
Hi, 
Firts of all big thanx for your work and this project. The one of interesting things for zephir popularization can be porting php с extension to zephir. PhpRedis for example. It`s can be nice and interesting project. 

But is any way to use sockets in zephir?

**Comment by phalcon** [comment]
Zephir can use any PHP function you may need: https://docs.zephir-lang.com/en/latest/functions.html

**Comment by JavaMachine** [comment]
@phalcon given above link is broken, where I can see documentation on using PHP functions?

**Comment by steffengy** [comment]
just as in PHP.
https://docs.zephir-lang.com/en/latest/functions.html
