### ISSUE TITLE
traces.m4:320: ERROR: end of file in string

### ISSUE THREAD

**Issue by etjson** [phalcon/zephir#2292]
![image](https://user-images.githubusercontent.com/41315967/134475790-ae6c8f93-970a-40d6-ab51-b6429290bcb0.png)

Preparing for PHP compilation...
/usr/bin/m4:/tmp/am4ty0flui/traces.m4:320: ERROR: end of file in string
unknown channel FIG is expanded from...
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level])
obsolete at /usr/share/autoconf/Autom4te/Channels.pm line 638.
        Autom4te::Channels::msg('FIG is expanded from...\x{a}build/libtool.m4:1917: _LT_AC_TAGCONF...', 'configure.ac:161', 'warning: back quotes and double quotes must not be escaped in...', 'partial', 1) called at /usr/bin/autom4te line 1026

What is the problem and how to deal with it ?

**Comment by Jeckerson** [comment]
Wrong end of line?

**Comment by etjson** [comment]
> Wrong end of line?

This exception is caused by the execution of phpize, how should I handle it?

**Comment by Jeckerson** [comment]
Please specify list of commands, and if necessary, minimal code to simulate your problem.
