### ISSUE TITLE
Port the "magic" of PHP to Zephir

### ISSUE THREAD

**Issue by taophp** [phalcon/zephir#398]
Hi,

It should be great if we can use "magic" methods (like `__set`, `__get`, `__call`, `__callStatic`) in Zephir the way we can in PHP, without the use of quotes and braces.

For example:

```zep
namespace Test;
class newIssue {
  public function __get(someProp){
    return "This is ".someProp;
  }
  public function printSomeProp(){
    echo this->someProp;
  }
}
```

Currently, we can accomplish the same thing (for `__get`, haven't check for others), but in an heavier way, replacing the `echo` line this way:

```
    echo this->{"someProp"};
```

**Comment by arthurpro** [comment]
I believe that magic methods in Zephir would be very useful.
I'd like to port one PHP library to Zephir but I got stuck with magic methods being heavily used in the library.
I'm  new to Zephir though, perhaps I can contribute to that feature development.
However, I'm not sure where to start at thia point.
Please advise!

**Comment by doanguyen** [comment]
Hi,

Just curious what's the status of this issue?

**Comment by sergeyklay** [comment]
As I know this feature has been implemented. If there are bugs, we can follow up in separate issues.
