### ISSUE TITLE
Debug Zephir without compile to C

### ISSUE THREAD

**Issue by loint** [phalcon/zephir#465]
Hi Zephir Team,

Phalcon is the fastest framework I've ever seen. Zephir is a great language too, but when I use Zephir to write my library and integrate it with Phalcon, I have some problems :

The compile time is long, Zephir compile to C, C compile to *.so file, attach to PHP and reload web server, it's complex and take a long time for me to debug. 
1. Is possible to debug Zephir without compile to C as well as attach to PHP ?
2. Can it run directly to console as an interpreters language ?

**Comment by feryardiant** [comment]
@ovr is it already available now?

I can't find anything about debugging zephir anywhere.
