### ISSUE TITLE
Travic CI PHP 5.3 Failed Sometimes with seg fault

### ISSUE THREAD

**Issue by ovr** [phalcon/zephir#510]
8 of 10 pull requests failed by this

@phalcon @nkt 

We can add this to failed matrix in travis.yml

**Comment by ovr** [comment]
Fixed, I will close

**Comment by TomasVotruba** [comment]
Hi, I keep getting this error on PHP 7.
https://travis-ci.org/Zenify/DoctrineFixtures/jobs/66739045#L139

Can do something about it? Thank you.
