### ISSUE TITLE
Functions in namespace

### ISSUE THREAD

**Issue by wapmorgan** [phalcon/zephir#517]
It does not support standalone functions in namespaces.
Please, consider providing this feature.
**Zephir, test/functions.php**
```php
namespace test;

function formatOutput(text) {
    // .. some stuff
}
```

**PHP 5.3**
```php
echo test\formatOutput('example');
```

**Comment by steffengy** [comment]
@ovr 
this is implemented now, issue should be closed.

**Comment by serg-deep** [comment]
Thank you. This is really great feature.
