### ISSUE TITLE
Can't overwrite the default array data if extends [$10 awarded]

### ISSUE THREAD

**Issue by mruz** [phalcon/zephir#537]
I can't set the default array data if extends:

``` zephir
class Test
{

    protected _data = [] { set, get };
}
```

``` php
<?php

class Users extends Test
{

    protected $_data = [
        'id', 
        'username', 
        'password', 
    ];
}
```

``` php
$user = new Users();
var_dump($user->getData())
```

> array(0) { }

Issue related to #520

**Comment by mruz** [comment]
> This bug is caused because PHP is not support default array value for properties
And we assign default array value in __constructor

It looks like it calls this assign after extends, @ovr could you confirm?

**Comment by steffengy** [comment]
@mruz Sure it does:
User::construct calls parent::construct (Test::construct), 
which it has to ensure that parent properties are set.

Can't think of a solution, which wouldn't require refactoring how it currently works.

**Comment by mruz** [comment]
@steffengy could user construct calls parent construct before user?

> Note: Parent constructors are not called implicitly if the child class defines a constructor. In order to run a parent constructor, a call to parent::__construct() within the child constructor is required. If the child does not define a constructor then it may be inherited from the parent class just like a normal class method (if it was not declared as private).

**Comment by mruz** [comment]
@sergeyklay @dreamsxin I have a feeling this issue returned. I will check/confirm it later.

**Comment by sergeyklay** [comment]
Feel free to open a new issue if the problem appears again.

**Comment by sergeyklay** [comment]
@mruz I found the issue. Working on solution

**Comment by sergeyklay** [comment]
Closing this one in favor of https://github.com/phalcon/zephir/issues/2089
