### ISSUE TITLE
Add support for operator overloading

### ISSUE THREAD

**Issue by nkt** [phalcon/zephir#541]
C extensions have API for overloading operators (GMP use it in 5.6)

**Comment by aurora** [comment]
Is this issue closed because it's already implemented or won't operator overloading make it into zephir?

**Comment by andrewdalpino** [comment]
For https://github.com/RubixML/Tensor

Would love to see this as it will enable Matrices and Vectors to be operated as such ...

c = a * b

as opposed to

c = a->multiply(b)
