### ISSUE TITLE
Support nested property-access

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#573]
``` zephir
namespace Debug;
class ZephirDebug
{
    public arr;

    public static function test()
    {
        let this->arr = new ZephirDebug();
        let this->arr->arr = 1;
    }
}
```

results in

```
Zephir\ParseException: Syntax error in /media/rdata/projects/XXX/zephir_debug/debug/zephirdebug.zep on line 9

                let this->arr->arr = 1;
        ----------------------^
```

Which is probably not expected behavior?
##

**Comment by aschwin** [comment]
What is the status of this? It is not closed yet, but is someone still working on this?

**Comment by sergeyklay** [comment]
+1

**Comment by steffengy** [comment]
I do not think anyone wouldn't want this feature but it's unfortunately
anything but easy to implement and would either consume very much time
or cause a very big performance degradation.
It's also not foreseeable at this point, when someone will have time for it, unfortunately.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/php-zephir-parser#16
