### ISSUE TITLE
Undefined index in ...

### ISSUE THREAD

**Issue by wapmorgan** [phalcon/zephir#583]
Have code:

``` zep
private data = [];

public function method() 
{
    var entry;
    let entry = current(this->data);
    return new Entry(entry);
}
```

Data is a two-dimensional array. Entry's constructor assigns array elements to own properties.

``` zep
let this->abc = entry[0]; // etc
```

And it fails with error: `Undefined index` for all assignments.
But if I change `method` to this:

``` zep
var entry; let entry = current(this->data);
var_dump(entry);
return new Entry(entry);
```

it works fine.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
