### ISSUE TITLE
Current tests on Windows

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#608]
I just tried running the tests on windows using phpunit, 
after an extension of mine just crashed somewhere around
array_update_multi/array_isset.

```
Can't register class Test\Oo::ExtendPdoClass with null parent
PHP Fatal error:  Unable to start test module in Unknown on line 0

Fatal error: Unable to start test module in Unknown on line 0
```
(PHP was compiled with PDO)

What is the issue here? Why does that happen when using windows?
Or am I doing something wrong, except using features, which aren't even a day old?

UPDATE:
Seems only to happen when compiling statically

**Comment by ovr** [comment]
Did you install PDO sqlite drivers for it?
