### ISSUE TITLE
Write Zephir in Zephir

### ISSUE THREAD

**Issue by andresgutierrez** [phalcon/zephir#637]
At some point, Zephir will allow us to write the AOT compiler itself in Zephir instead of using PHP. Keeping this thread open for discussion.
##

**Comment by gouchaoer** [comment]
php7 is improving, especcialy on performance(jit will merge into master soon) and static type(we now have scalar typehint in function parameter). it has prooved that in a normal application(the opened issue) zephir has the same performance as php. i can not see any advantage on using zephir to write zephir. zephir is not a meta-language of php(you can not translate it into php) but they all run on php runtime. i think zephir should keep close to php, be able to utilize php's libs and make up drawbacks of php, not stay away from php.

**Comment by Jurigag** [comment]
Anyway idea of runtime and writing zephir code in zephir i think was dropped but not sure about it, compilation of this runtime think is not possible atm i last checked.

**Comment by sergeyklay** [comment]
To become a Turing-complete (or Turing-powerful) Zephir has to be written on Zephir. To achieve this we can introduce a brand new backed (say `C++Backend`, or `GolangBackend`). This will allow us to create programs that can work without Zend Engine support.

**Comment by danhunsaker** [comment]
This isn't to say ZendEngine backends will go away. That wouldn't serve any purpose, here. Instead, the proposed new backend would be an additional one. (For those who didn't catch that above...)
