### ISSUE TITLE
Zephir Portability & Distribution Strategy

### ISSUE THREAD

**Issue by chrismervyn** [phalcon/zephir#646]
First up, guys kudos on an awesome project! Love it!
Now, I am evaluating Zephir for around 3 months now and I have done almost all my research and am about to embark upon a project armed with Zephir. This is a PHP-Mysql-ShellScript-Py based software on LAMP that we install at customer's premises. We are moving from PHP to Zephir[80%] + PHP[for class extension purposes which will be unique towards each customer]. Now, we have dev machines where we would test/run the project. I understand every part of it. How should we go about deploying the project in the customer's premises? Can we not distribute pre-compiled Zephir generated Libs? or do we have to compile it at the customer's end?

**Comment by ankitmlive** [comment]
Hey @chrismervyn 

Have you fixed your problem.please help me.
I have completed the project in local dev machine and now wants to deploy it on a production debian server.
I have compiled `xyz.so` file in my local dev machine with the same configuration as production server and uploaded it to `/usr/lib/php/20154845/xyz.so ` but its not working.

Should i install zephir on production server and compile it ? please explain
