### ISSUE TITLE
Namespace 'nazarpc' must be in camelized-form

### ISSUE THREAD

**Issue by nazar-pc** [phalcon/zephir#662]
I have this namespace in my composer packages, and I want to use it here, but zephir gives stupid error.
Fortunately, if I just comment it out - it compiles just fine.
What was the reason for this decision?

**Comment by alanwillms** [comment]
@nazar-pc how did you solve this?

**Comment by nazar-pc** [comment]
@alanwillms initially I've edited source code, but I've encountered few other problems afterwards.
Since no one answered for some of them and I wasn't able to solve them - I just gave up.
Zephir is not currently usable for me.

**Comment by alanwillms** [comment]
@phalcon What if I am converting part of an existing package for optimization purposes? I would have to change my entire package to follow Zephir namespace name convention. I think this is still a valid issue.

**Comment by andresgutierrez** [comment]
@alanwillms If anyone wants to submit a change implementing this I'll be happy in merging it

**Comment by alanwillms** [comment]
@andresgutierrez I don't know C enough to do that. Can you reopen this issue so that it becomes visible for someone willing to solve it? :blush:

**Comment by nazar-pc** [comment]
As I said in first message - just commenting check that namespace should start with capital letter worked for me.

**Comment by andresgutierrez** [comment]
@alanwillms You don't need to know C, Zephir is written in PHP

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
