### ISSUE TITLE
Php to zephir

### ISSUE THREAD

**Issue by fezfez** [phalcon/zephir#676]
hi,

I'm currently working on project that convert php to zephir using an AST.
It allready translate some project ex : symfony/event-dispatcher, doctrine/instanciator...

If you are interest, take a look at https://github.com/fezfez/php-to-zephir !

Thanks for your work.

**Comment by jimthunderbird** [comment]
Fezfez, I created a tool on top of the PHP Parser and your work, just making developers to more comfortably write php extension with php, feel  free to check out:
https://github.com/jimthunderbird/php-to-c-extension

**Comment by fezfez** [comment]
Close, not an issue.
