### ISSUE TITLE
Segmentation fault  with elseif fetch 

### ISSUE THREAD

**Issue by brainformatik** [phalcon/zephir#685]
tested with the latest zephir version (396cb30842ae6cb1ecc1466b09c3690d025e4292).

we get a segmentation fault in **elseif** statement

``` php
if fetch myVar, checkIssetVar {
   //do some stuff
} elseif fetch myVar, checkIssetVar {
   //do some stuff
}
```
##

**Comment by sergeyklay** [comment]
`fetch` is reserved keyword

https://github.com/phalcon/zephir/issues/1269
