### ISSUE TITLE
Zephir Performance vs PHP

### ISSUE THREAD

**Issue by ovr** [phalcon/zephir#694]
Original question was sent to me by email from @dgafka

> So my question to you are.
> Do I test it wrong or Zephir should be used to something else? 
> Links, to repositories with tests:
> https://github.com/dgafka/Php-BookStore
> https://github.com/dgafka/zephir-BookStore

And my history

I've written 2 applications in Zephir
In a big application It was better than PHP - 10%
but in small lib it was slower - 1-2%

I think we have places with awful performance :anguished: 

Cc: @andresgutierrez @phalcon @nkt @niden @racklin

**Comment by jimthunderbird** [comment]
I guess zephir is great for optimizing loops, also, the flexibility of embedded C code in zephir is great. In my tool php-to-c-extension, it shows great result buy using zephir's way of embbed C code and the implementation of bubble sort. It is more than 100 times faster than pure PHP version.

https://github.com/jimthunderbird/php-to-c-extension#example-13

**Comment by gouchaoer** [comment]
today i want to express the reason why zephir is not faster in real application.
zephir is a great work and so does phalcon. it is fsatest in hello-workd benchmark. but hello-world benchmark has no io(redis/mysql...), the php-fpm is always eat 100% cpu and no blocking. this is not true. in real-world application, php-fpm is always blocking at io. the cpu is costed in switching from php-fpm to php-fpm, so zephir/php act the same. bottleneck is io.

reactphp/swoole/workerman is async io framework and can solve this problem. but async callback is a hell. some framework use yield to implement a semi-coroutine like js's koa. they have great performance in real world applications. but semi-coroutine is not as easy as blocking php-fpm apps. so swoole2 implement php's own coroutine and now we can write io heavy real world apps like go.

hope to help you

**Comment by Jurigag** [comment]
Yea bottleneck is io for sure. But still, it's still faster than laravel/symfony in real application even with database.

**Comment by gouchaoer** [comment]
did you run a flame graph to detect what's the bottleneck?
openresty community heavily utilize flame graph to detect what exeactly the line of code cause the bottleneck and fix it.

**Comment by fakharak** [comment]
I developed CrustPHP using Swoole and Phalcon Micro components and shipped blazing-fast APIs.
[Link to CrustPHP](https://github.com/fakharak/CrustPHP)
