### ISSUE TITLE
Magic constants

### ISSUE THREAD

**Issue by nblaudez** [phalcon/zephir#71]
Can we use magic constants as **DIR** or **METHOD** with zephir, compiler return me an error when i use **DIR**

**Comment by mruz** [comment]
@ovr I would like to set `__ROOT__` constant for root path in the di contructor, to dir where di is created, can I access to php's `__DIR__`?
```zep
if !defined("__ROOT__") {
    define("__ROOT__", dirname(__DIR__), false);
}
```

As you know:
> Warning: Magic constant `__DIR__` is not supported in /home/mruz/Dropbox/git/ice/framework/ice/di.zep on 28 [not-supported-magic-constant]

**Comment by ovr** [comment]
@mruz 
`is not supported`

**Comment by mruz** [comment]
Any chance to add support? enough `__FILE__`, it can be useful.

**Comment by fightingbamboo** [comment]
when to add full support?

**Comment by romizone** [comment]
dirname( __FILE__ ) 
Anybody knows whether it is supported by Zephir ?

I have problem placing those code inside Zephir in Eval() functions

**Comment by sergeyklay** [comment]
@romizone Could you please open a new issue with script to reproduce
