### ISSUE TITLE
[NFR] ClassDefinition implement docblock

### ISSUE THREAD

**Issue by ovr** [phalcon/zephir#713]
Need to implement getting for docblocks for `ClassDefinition`
 and `stubs` generator for it

**Comment by mruz** [comment]
+1

**Comment by mruz** [comment]
I think this is done via https://github.com/phalcon/zephir/commit/cefdc33b28c674b8caf09fe1a15e488dd53cae8e.

**Comment by ovr** [comment]
@mruz Yeap, I will close this
