### ISSUE TITLE
[NFR] Ternary conditional operator

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir#722]
Please add support for short syntax of ternary conditional operator:

```zephir
namespace Foo;

class Bar
{
    public function test(string! a, string b=null) -> string
    {

        // currently works fine
        let b = (b === null) ? a : b;

        // does not work
        let b = b ?: a;

        return b;
    }
}
```

Thanks

**Comment by ovr** [comment]
I am working on it

**Comment by sergeyklay** [comment]
Is there any progress?

**Comment by sergeyklay** [comment]
@ovr @steffengy any progress?

**Comment by ovr** [comment]
@sergeyklay 
https://github.com/phalcon/zephir/pull/723 I started but didnt finish
I will try to finish it, tomorrow 8 november
