### ISSUE TITLE
Superglobals like _GET not globally mutable

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#725]
If you do something like below _GET["test"] will only be modified in that specific function,
but when you access it from another scope 
(for example from another function or generally code that runs later), 
the value and therefor the superglobal remains unchanged.

```
public static function test()
{
    let _GET["test"] = 1;
}
```

Could be because of PH_SEPARATE?

**Comment by ovr** [comment]
Please added more tests for all types

**Comment by steffengy** [comment]
@ovr Done. Just didn't get to it yesterday
