### ISSUE TITLE
[NFR] for & foreach

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir#741]
From the current documentation

> A `for` is a control structure that allows to traverse arrays or strings:

Hmm.. Frankly it's like a `foreach`. but where are `for`?!
C/C++ and PHP have `foreach` and `for`.

What about the full (conventional) support for `for`?

``` php
for ($i = 0; $i < 10; $i++) {
    echo $i;
}
```

Thanks

**Comment by mruz** [comment]
What about?
```zep
for i in range(0, 9) {
    echo i;
}
```

**Comment by sergeyklay** [comment]
@mruz yes, you're right, exactly in this example current implementation of `for` is enough.

But, when need to increase the counter not by 1?
Or, another example:

```php
for($col = 'R'; $col != 'AD'; $col++) {
    echo $col.' ';
}

// returns: R S T U V W X Y Z AA AB AC
```

**Comment by sergeyklay** [comment]
another php example
```php
for( ; $iterator->valid(); $iterator->next()) {
    // something
}
```

Of course, this is solved by a `while`, but the flexibility of language lies in the diversity of its methods and timely using of these methods

**Comment by jimthunderbird** [comment]
Using my tool:

https://github.com/jimthunderbird/php-to-c-extension#example-04

You   can do for loop in php, internally it's using the equivalent while loop.

**Comment by xutongle** [comment]
```
for ($i = 0; $i <= 10; $i++) {
    echo $i;
}
```
碰到这种很郁闷

**Comment by jimthunderbird** [comment]
我写了一个转换工具, 会把for转成while.所以有和没有for在zephir里都无所谓。https://github.com/jimthunderbird/php-to-c-extension/blob/master/README.md#example-04

**Comment by jimthunderbird** [comment]
用WHILE就可以解决了，有兴趣请参考我的工具，用PHP自动生成ZEPHIR，而且可以将PHP FOR LOOP转成WHILE LOOP。
https://github.com/jimthunderbird/php-to-c-extension#example-12
以后ZEPHIR全支持FOR LOOP最好，现在用WHILE是一个暂时的办法。
