### ISSUE TITLE
Can't use levenshtein function.

### ISSUE THREAD

**Issue by coollider** [phalcon/zephir#753]
When call levenshtein function get this error.

```php
Zephir\CompilerException: The number of parameters passed is lesser than the number of required parameters by 'levenshtein' in Str.zep on line 348

	        levenshtein(pattern, str);
	---------------------------------^
```

**Comment by ovr** [comment]
Fix was merged into PHP 5.5+
Will be released in upcoming minors versions

5.6.7
5.5.23

**Comment by serg-deep** [comment]
Thanks!

**Comment by nkt** [comment]
@ovr so it's not Zephir bug?

**Comment by ovr** [comment]
@nkt It's not a Zephir bug, but we need to create optimizers for it (better perfomance)
