### ISSUE TITLE
Error when try/catch in if/else command ?

### ISSUE THREAD

**Issue by MaxCodeX** [phalcon/zephir#755]
I found a bug, when build code same below

File --> Test.zep;

class Test {

	public function __construct () {
		var e;
		if("a"=="b"){
			try{
				echo "a";
			}catch \Exception,e {
				echo e->getMessage();
			}
		}else{
			try{
				echo "b";
			}catch \Exception,e {
				echo e->getMessage();
			}
		}
	}
}

- How to fix it, help me

**Comment by MaxCodeX** [comment]
Compile-error.log 

/media/DataExt4/Working/libtools/ext/libtools/test.zep.c: In function 'zim_Libtools_Test___construct':
/media/DataExt4/Working/libtools/ext/libtools/test.zep.c:61:3: error: duplicate label 'try_end_1'
/media/DataExt4/Working/libtools/ext/libtools/test.zep.c:44:3: note: previous definition of 'try_end_1' was here
make: *** [libtools/test.lo] Error 1
/media/DataExt4/Working/libtools/ext/libtools/test.zep.c: In function 'zim_Libtools_Test___construct':
/media/DataExt4/Working/libtools/ext/libtools/test.zep.c:61:3: error: duplicate label 'try_end_1'
/media/DataExt4/Working/libtools/ext/libtools/test.zep.c:44:3: note: previous definition of 'try_end_1' was here
make: *** [libtools/test.lo] Error 1

**Comment by valVk** [comment]
Can confirm that.
```
		if !suppress_error && !this->silence_connection_warning {
			try {
				let con = new \Pdo(dsn);
			} catch \PDOException, e {
				trigger_error("connection error", E_USER_WARNING);
			}
		} else {
			try {
				let con = new \Pdo(dsn);
			} catch \PDOException, e {
				throw new ConnectionException(e->getMessage());
			}
		}
```

log

```
/work/zephir-projects/foolzc/ext/foolzc/sphinxql/drivers/pdoconnection.zep.c: In function 'zim_FoolzC_SphinxQL_Drivers_PdoConnection_connect':
/work/zephir-projects/foolzc/ext/foolzc/sphinxql/drivers/pdoconnection.zep.c:352:3: error: duplicate label 'try_end_1'
   try_end_1:
   ^
/work/zephir-projects/foolzc/ext/foolzc/sphinxql/drivers/pdoconnection.zep.c:329:3: note: previous definition of 'try_end_1' was here
   try_end_1:
   ^
```

pdoconnection.zep.c

```
if (_6) {

		/* try_start_1: */

			ZEPHIR_INIT_NVAR(con);
			object_init_ex(con, php_pdo_get_dbh_ce());
			ZEPHIR_CALL_METHOD(NULL, con, "__construct", NULL, dsn);
			zephir_check_call_status_or_jump(try_end_1);

		try_end_1:

		if (EG(exception)) {
			ZEPHIR_CPY_WRT(e, EG(exception));
			if (zephir_instance_of_ev(e, php_pdo_get_exception() TSRMLS_CC)) {
				zend_clear_exception(TSRMLS_C);
				ZEPHIR_SINIT_VAR(_8);
				ZVAL_STRING(&_8, "connection error", 0);
				ZEPHIR_SINIT_VAR(_9);
				ZVAL_LONG(&_9, 512);
				ZEPHIR_CALL_FUNCTION(NULL, "trigger_error", &_10, &_8, &_9);
				zephir_check_call_status();
			}
		}
	} else {

		/* try_start_1: */

			ZEPHIR_INIT_NVAR(con);
			object_init_ex(con, php_pdo_get_dbh_ce());
			ZEPHIR_CALL_METHOD(NULL, con, "__construct", NULL, dsn);
			zephir_check_call_status_or_jump(try_end_1);

		try_end_1:

		if (EG(exception)) {
			ZEPHIR_CPY_WRT(e, EG(exception));
			if (zephir_instance_of_ev(e, php_pdo_get_exception() TSRMLS_CC)) {
				zend_clear_exception(TSRMLS_C);
				ZEPHIR_INIT_VAR(_11);
				object_init_ex(_11, foolzc_sphinxql_exception_connectionexception_ce);
				ZEPHIR_CALL_METHOD(&_12, e, "getmessage", NULL);
				zephir_check_call_status();
				ZEPHIR_CALL_METHOD(NULL, _11, "__construct", NULL, _12);
				zephir_check_call_status();
				zephir_throw_exception_debug(_11, "foolzc/sphinxql/drivers/pdoconnection.zep", 162 TSRMLS_CC);
				ZEPHIR_MM_RESTORE();
				return;
			}
		}
	}
```

seems that we can use only 1 try/catch in single method. becase there is no incremental for aliases.

**Comment by valVk** [comment]
As temporary solution suggest use only one try/catch per method. If you need use two and more than move all others try/catch blocks to the additional methods.

**Comment by andresgutierrez** [comment]
This is fixed in master

**Comment by valVk** [comment]
Hi.

I get all latest changes  my zephir version is 0.6.1a
I've made:
* zephir compile
* zephir clean
* zephir fullclean
* zephir build

But I still get the errors which were reported here. What I missed up?

Thanks.

**Comment by valVk** [comment]
thanks
