### ISSUE TITLE
in place update of array element in zephir

### ISSUE THREAD

**Issue by jimthunderbird** [phalcon/zephir#758]
What is the zephir way of doing the following?
$tmp = $arr[$i];
$arr[$i] = $arr[$i + 1];
$arr[$i + 1] = tmp;

**Comment by steffengy** [comment]
something like
```
var tmp;
let tmp = arr[i];
let arr[i] = arr[i + 1];
let arr[i + 1] = tmp;
```
should work fine, doesn't it?

**Comment by jimthunderbird** [comment]
Yes that works great.
