### ISSUE TITLE
Cannot use `in` as method name in class definition.

### ISSUE THREAD

**Issue by dkraczkowski** [phalcon/zephir#761]
Hi! I am trying to define abstract class which contains method with name `in` like in the example below:
```
abstract class AbstractFinder
{
    //...
    public function in(string dirname)
    {
        //..
    }
}
```

AFAIK `in` is not a keyword in PHP's world, but in zephir I am getting syntax error:

```
Syntax error in ...AbstractFinder.zep on line 98

	    public function "in"(string dir)
	-----------------------^
```

Any suggestions/help how to fix it? Thanks.

**Comment by steffengy** [comment]
try public function $in(string dir)

**Comment by ovr** [comment]
Closed via good answer from @steffengy

**Comment by dkraczkowski** [comment]
Thanks:)
