### ISSUE TITLE
Invalid callback, cannot access private method

### ISSUE THREAD

**Issue by ghost** [phalcon/zephir#764]
```
//main.zep
namespace Coba;

class Main
{
    public function init()
    {
        echo "INIT<br>";
        this->test();
    }

    private function test()
    {
        echo "TEST<b>";
    }
}

```

Call from php script

```
class Nasi extends \Coba\Main
{
    function makan()
    {
        $this->init();
    }
}

$x = new Nasi();
$x->makan();
```

PHP Warning:  Invalid callback Nasi::test, cannot access private method Nasi::test() in ........
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Call to undefined method Nasi::test(), did you mean 'test'?' in.............

Rewrite main class as php script, everything is fine,,,

What's wrong??
##

**Comment by andresgutierrez** [comment]
Can you please try again?

**Comment by wskdf** [comment]
Same to same

[Mon Apr 20 13:05:02 2015] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Call to undefined method Nasi::test(), did you mean 'test'?'

```zephir version```
0.6.2a

```git log```
commit 941cd3ea858ba78aeafe7169cf222b83f53641a2
Merge: 95cccb1 80eea0b
Author: Andres Gutierrez <gutierrezandresfelipe@gmail.com>
Date:   Sun Apr 19 10:20:14 2015 -0500

**Comment by steffengy** [comment]
Works for me, what PHP version are you using?

**Comment by wskdf** [comment]
PHP 5.3.10-1ubuntu3.17 with Suhosin-Patch (cli) (built: Mar 17 2015 12:00:21)
