### ISSUE TITLE
Expression in case statement

### ISSUE THREAD

**Issue by SliceOfLife** [phalcon/zephir#768]
Can I use an expression in case statement?

```zep
		switch(true) {
			case 1 > 0:
				echo 1;
		}
```
This code throw a syntax error on compiling.

**Comment by fezfez** [comment]
It's not possible.

I encounter this case with php-to-zephir translator and symfony/event-dispatcher. The solution was to translate switch to if.

**Comment by SliceOfLife** [comment]
I already rewrite the code to use if instead of switch, but it looks ugly :(

**Comment by ovr** [comment]
It's not implemented
Why do you need it?

```php
case 1 > 0
```

Can you show a good example?

**Comment by SliceOfLife** [comment]
For example

```zep
switch (true) {
	case var1 > 10 && var1 < 20:
	case var2 == var1:
	case var2 > 100500:
		return sprintf("var1 = %d, var2 = %d", var1, var2);

	case var2 < 0:
	case var1 <= 10 || var1 >= 20:
		throw new \Exception();
}
```

Instead of this I should use if:

```zep
if (var1 > 10 && var1 < 20) || (var2 == var1) || (var2 > 100500) {
	return sprintf("var1 = %d, var2 = %d", var1, var2);
} elseif (var2 < 0) || (var1 <= 10 || var1 >= 20) {
	throw new \Exception();
}
```

It's similar, but looks not so clearly.
