### ISSUE TITLE
Potential Duplicate Code in Zephir\Compiler::generate() 

### ISSUE THREAD

**Issue by pjacferreira** [phalcon/zephir#772]
Hi, 

As per a request by zyxep (from IRC) I have created this issue.

I was doing a little debugging of the PHALCON 2 Zephir Code and noticed something strange.
In the method Zephir\Compiler::generate() I noticed that lines 686 - 714 are repeated (again) at positions 749 - 778.

I wasn't sure if this was intentional (i.e. a 2 pass compiler system) or not?

**Comment by ovr** [comment]
Thank for feedback
Will be reviewed ASAP

**Comment by ovr** [comment]
Fixed by @steffengy
