### ISSUE TITLE
"__" as function name

### ISSUE THREAD

**Issue by mruz** [phalcon/zephir#779]
I'm trying to add global function which is called "__" (easy and short) to translate strings https://github.com/phalcon/zephir/pull/762 and I'm getting:
```
Zephir\ParseException: Syntax error in /home/mruz/Dropbox/git/ice/framework/ice/i18n.zep on line 1

        function __(string! str, array values = null, string lang = null)
        -----------^

```

**Comment by steffengy** [comment]
It might be that `_` is reserved or something.
Have you tried using `$__` and does that work?
it does work when you use a name not only consisting of `_` right?

**Comment by mruz** [comment]
With single `_` char works, also with other name like `t`, but I just like to use `__` :) 
The `$` does not change anything, because it is used for zephir reserved words only.

**Comment by nkt** [comment]
@ovr I guess this is bug. In parser IDENTIFIER is matches to `[\\_\$]?[_a-zA-Z\\][a-zA-Z0-9\_\\]*`

**Comment by mruz** [comment]
@phalcon https://github.com/phalcon/zephir/commit/425385e4287ff0b6c0929110753a8881e9bb86d0 any idea to also allow double underscores as identifier?

**Comment by mruz** [comment]
@andresgutierrez Is it enough to add this to the parser/scanner.re?
```
if (token->len == 2 && !memcmp(token->value, "__", sizeof("__")-1)) {
        token->opcode = XX_T_IDENTIFIER;
        return 0;
}
```

**Comment by nkt** [comment]
@mruz you're right, but this is a big hack. @andresgutierrez we should remove defining constants in parser.
