### ISSUE TITLE
Broken str_replace behavior

### ISSUE THREAD

**Issue by SliceOfLife** [phalcon/zephir#802]
In PHP str_replace accept array as first and second parameters, but in Zephir we can't use this feature:

```zep
	public static function doSomething()
	{
		var arr;

		let arr = ["a", "b", "c"];

		var_dump(str_replace(arr, "", "apple juice is amazing delicious"));
	}
```

This code produces "NULL".

Zephir 0.6.0a

**Comment by mruz** [comment]
Duplicated https://github.com/phalcon/zephir/issues/732

**Comment by serg-deep** [comment]
+1

**Comment by mruz** [comment]
Temporarily you can use loop like in friendlyTitle https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/tag.zep#L1370

**Comment by SliceOfLife** [comment]
Yes, yes, we can.
But this behavior violations broke ported PHP code in unexpected points without any compiler or parser warnings.

**Comment by nkt** [comment]
Duplicate of #732
