### ISSUE TITLE
Add readonly property for classes in Zephir.

### ISSUE THREAD

**Issue by coollider** [phalcon/zephir#809]
Php extensions support read only properties for classes. Example http://php.net/manual/ru/class.domelement.php, $schemaTypeInfo and $tagName read only. Maybe add it to Zephir?

**Comment by andresgutierrez** [comment]
Those properties use magic getters to ensure the properties aren't writable to the PHP userland.

**Comment by serg-deep** [comment]
Ty. I did not know about it. You can close this issue.
