### ISSUE TITLE
Add declare + init varaibles to Zephir.

### ISSUE THREAD

**Issue by serg-deep** [phalcon/zephir#810]
In Zephir we must first declare variable, and only then we can use it.
```php
var
  simpleVar;
let
  simpleVar = 1;
```
Why we cat't use this?
```php
var
  simpleVar = 1;
```

**Comment by loint** [comment]
yes, I think it 's great if we can use this syntax. @ovr Do you have any idea for this case ?

**Comment by hylent** [comment]
`var simpleVar = 1;`

It is already supported, am I right?

**Comment by ovr** [comment]
It's already supported

**Comment by ovr** [comment]
I will close, comment if it's not okey
