### ISSUE TITLE
CI for Windows builds

### ISSUE THREAD

**Issue by ovr** [phalcon/zephir#817]
I am going to use AppVeyor for Windows CI builds

http://www.appveyor.com/

**Comment by loint** [comment]
:+1:

**Comment by steffengy** [comment]
+1 But probably unit tests wont pass yet, see #608

**Comment by andresgutierrez** [comment]
:+1:

**Comment by steffengy** [comment]
@ovr 
any progress on this?
I'm also open to implement this.

**Comment by ovr** [comment]
@steffengy 
No progress
Will be perfect, if you will implement it ;)

**Comment by steffengy** [comment]
@ovr hopefully the major part is be done (see PR)

**Comment by steffengy** [comment]
I think this is pretty much implemented now.
Does anybody have an idea how to solve updating the zephir-parser.exe binary?
Possibilities:
- keep it as it is, manually update it
- use appveyor to update it automatically, if the binary changes (which is eventually hard to detect)
- store the binary separately and use a "wrapper script" which always checks (if internet is available) if a newer version is available (and downloads one if so)

@andresgutierrez  any better idea/preference?

**Comment by ovr** [comment]
> manually update it

Steps before releases

- Generate parser
- Bump version in core
- Release new tag

**Comment by steffengy** [comment]
@ovr
Also a possibility (hasn't happened for 0.6.1 though).

The only problem I see, is the situation we currently have:

The parser get's updated and the tests/new syntax and you
can't test/use it on win32, without rebuilding or fetching
a rebuilt executable from appveyor.

**Comment by andresgutierrez** [comment]
@steffengy I think we have to manually update it before tag a new version

**Comment by steffengy** [comment]
@andresgutierrez 
Ok, it should be done consequently then though :)
It's also pretty easy now, since you just can download the latest parser from the latest appveyor build :)

**Comment by ovr** [comment]
Will close issue, via implemented by @steffengy
