### ISSUE TITLE
Add generated C files to gitignore

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#823]
This is something that is a bit annoying for some time now:

**I think generated C-files (everything in ext/test) should be added to gitignore.**
(Maybe instead remove the whole ext folder and relocate kernel to some other directory?)

The current state, with generated C-files in the repository, leads to:
- **An outdated state**, when generated files are not commited, leading to uncommited
changes in the local worktree, if you just compile zephir.
- **Intransparent commits**, when a commit contains a single change and several regenerated files, which make the change harder to notice.

I personally also do not see any reason to keep these generated C-files in the repository,
since they just can be generated using the compiler, and are by no means source files,
which are regularily updated by people, but automatically.

I think they just cause "polluted" commits, with unnecessary changes.

Is there any reason to store them there?
And if so, does that really justify these negative consequences?

**Comment by ovr** [comment]
For Phalcon 2 I am going :+1:,
but for development of Zephir
See what's changed in latests commits (i mean regenerated code with new optimization) is rly needed

I think We need to create unchanged tracker for CI to prevent not regenerated sources from commits

**Comment by steffengy** [comment]
Then I think it would atleast be better to use separate commits that actual changes are clearly visible.

@ovr what do you think about that proposition?

**Comment by andresgutierrez** [comment]
-1

We need to easily check the code generated for discussing purposses

**Comment by steffengy** [comment]
@andresgutierrez i understand what you mean but when you have a commit consisting of multiple changes and regenerated code in between, it makes it harder to see what actually changed.
But as I understand, you are also against splitting it into multiple commits?
If so it should atleast be ensured that the most current version of generated code is commited.
