### ISSUE TITLE
Syntax error when trying to build Zephir

### ISSUE THREAD

**Issue by BonnieDoug** [phalcon/zephir#824]
Just gone through the install steps for Zephir, but once I get to the Zephir Build step I get the following error:

    c:\zephir>zephir build
    Zephir\ParseException: Syntax error in C:\zephir\test\fcall.zep on line 7

        function zephir_global_method_test(var str)
        -------^

    at Library\CompilerFile.php(534)
    #0 Library\Compiler.php(159): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
    #1 Library\Compiler.php(199): Zephir\Compiler->preCompile('test\fcall.zep')
    #2 Library\Compiler.php(686): Zephir\Compiler->recursivePreCompile('test')
    #3 Library\Compiler.php(880): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
    #4 Library\Compiler.php(985): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
    #5 Library\Compiler.php(1054): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
    #6 Library\Commands\CommandAbstract.php(72): Zephir\Compiler>build(Object(Zephir\Commands\CommandBuild))
    #7 Library\Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
    #8 compiler.php(21): Zephir\Bootstrap::boot()
    #9 {main}

This is using php 5.6 nts with VS2012.

System PATH currently has these (Plus many more)

    C:\xampp\php; //(5.5 nts)
    C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
    C:\zephir\bin;
    C:\phpdevpack; //(php-5.6.6-nts-Win32-VC11-x86.zip)
    C:\phpsdk; //(php-sdk-binary-tools-20110915.zip)

Not to sure what else to put here but I'll happily supply any other info needed.

**Comment by ovr** [comment]
Did you recompile a parser?

**Comment by BonnieDoug** [comment]
All I've done is follow the steps as described here https://github.com/phalcon/zephir/blob/master/WINDOWS.md except for the setx commands were failing with a "WARNING: The data being saved is truncated to 1024 characters." error, so I set them manually in System/Advanced System Settings/Environmental Variables/Path

**Comment by andresgutierrez** [comment]
You need a visibility before 'function': public, protected, private, etc

**Comment by BonnieDoug** [comment]
I've not modified the code in anyway yet, all I've done is clone the current repo from github. I'm only trying to test phalcon 2 at the moment.

**Comment by BonnieDoug** [comment]
Have removed the thread safe xampp 5.5 PHP in favour of 5.6 nts updated PHP dev tools for 5.6 but still have the same error regarding incorrect syntax on line 7

**Comment by steffengy** [comment]
Its because the windows zephir compiler binary hasnt been updated yet.
@andresgutierrez Is it ok to replace the cygwin binaries with native msvc binaries? (As my jsonc patch allows)
If so, I could do the PR for that.

**Comment by BonnieDoug** [comment]
Is there anything I can do to get around this (without installing Linux) ?

**Comment by steffengy** [comment]
You need a newer version of the win32 parser, which you could build yourself
Else you will have to wait until somebody updates the binary or use the one from my zephir-ng branch.

**Comment by BonnieDoug** [comment]
Think I'll try the last option :-) will forking your repo and trying to build it succeed do you think.

On a side note, is there a reason why 2.0 dlls aren't simply downloadable like the 1.3.* are? Is it an effort to push all phalcon devs to dabble in zephir?

**Comment by ovr** [comment]
@steffengy 
Can you please create PR with latest regenerated parser?

**Comment by andresgutierrez** [comment]
@steffengy yes, could you please submit a regenerated parser?

**Comment by steffengy** [comment]
Ok I Will commit it with instructions very soon :)

**Comment by ovr** [comment]
Seems to be okey, will close
