### ISSUE TITLE
Zend Memory

### ISSUE THREAD

**Issue by rdjpg** [phalcon/zephir#825]
I tried convert my PHP script (project) to Zephir. But give me error message "zend_mm_heap corrupted" in apache error.log.

Yes, this is not zephir problem. My coding technique is not right :D

But why that message come, when the php script is not?
Zephir care of memory as well as it does with php script, right?

**Comment by ovr** [comment]
I think memory was leaked

Can you run this script under valgrind with PHP CLI SAPI?

```sh
$ valgrind php script.php
```

https://github.com/phalcon/zephir/blob/master/CONTRIBUTING.md#bugs

**Comment by rdjpg** [comment]
```
$ valgrind php index.php
```
==8217== Memcheck, a memory error detector
==8217== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==8217== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==8217== Command: php index.php
==8217== 
PHP Warning:  Invalid arguments supplied for strpos() in /home/rdjpg/public_html/roda/index.php on line 30
PHP Warning:  Invalid arguments supplied for strpos() in /home/rdjpg/public_html/roda/index.php on line 30
TEST PAGE==8217== 
==8217== HEAP SUMMARY:
==8217==     in use at exit: 74,650 bytes in 215 blocks
==8217==   total heap usage: 32,877 allocs, 32,662 frees, 5,697,739 bytes allocated
==8217== 
==8217== LEAK SUMMARY:
==8217==    definitely lost: 6,906 bytes in 9 blocks
==8217==    indirectly lost: 8,610 bytes in 12 blocks
==8217==      possibly lost: 0 bytes in 0 blocks
==8217==    still reachable: 59,134 bytes in 194 blocks
==8217==         suppressed: 0 bytes in 0 blocks
==8217== Rerun with --leak-check=full to see details of leaked memory
==8217== 
==8217== For counts of detected and suppressed errors, rerun with: -v
==8217== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 2 from 2)


> btw, "zend_mm_heap corrupted" not always show in every request. but sometimes,,,

**Comment by andresgutierrez** [comment]
Could you please try again using latest master?
