### ISSUE TITLE
SubstrOptimizer disabled, what bugs has the implementation?

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#833]
The substring optimizer is disabled since 1ba122246415bc4f79eabe4012bef975e4050eb8
which isn't quite optimal, since it's one of the most common functions.

A comment says it's implementation has bugs:

Does anybody know **what** bugs?

@andresgutierrez 
Do you recall what bugs?

**Comment by andresgutierrez** [comment]
It does not work passing an array as first parameter

**Comment by steffengy** [comment]
@andresgutierrez 
PHP's behavior is to just throw a warning and return null:
```substr() expects parameter 1 to be string, array given on line```
current behavior (with pached #834) is to cause:
```Notice: Array to string conversion```

should that be adjusted?
