### ISSUE TITLE
Zephir build failed

### ISSUE THREAD

**Issue by serg-deep** [phalcon/zephir#838]
In file included from /usr/share/php/libs/it/ext/kernel/main.c:29:0:
./kernel/main.h:20:0: error: unterminated #ifndef
 #ifndef ZEPHIR_KERNEL_MAIN_H
 ^
In file included from ./kernel/fcall.h:25:0,
                 from /usr/share/php/libs/it/ext/kernel/main.c:31:
./kernel/main.h:20:0: error: unterminated #ifndef
 #ifndef ZEPHIR_KERNEL_MAIN_H
 ^
make: *** [kernel/main.lo] Error 1
make: *** Waiting for unfinished jobs....
In file included from /usr/share/php/libs/it/ext/it.c:23:0:
/usr/share/php/libs/it/ext/kernel/main.h:20:0: error: unterminated #ifndef
 #ifndef ZEPHIR_KERNEL_MAIN_H
 ^
In file included from /usr/share/php/libs/it/ext/kernel/fcall.h:25:0,
                 from /usr/share/php/libs/it/ext/it.c:24:
./kernel/main.h:20:0: error: unterminated #ifndef
 #ifndef ZEPHIR_KERNEL_MAIN_H
 ^
make: *** [it.lo] Error 1
In file included from /usr/share/php/libs/it/ext/it.c:23:0:
/usr/share/php/libs/it/ext/kernel/main.h:20:0: error: unterminated #ifndef
 #ifndef ZEPHIR_KERNEL_MAIN_H
 ^
In file included from /usr/share/php/libs/it/ext/kernel/fcall.h:25:0,
                 from /usr/share/php/libs/it/ext/it.c:24:
./kernel/main.h:20:0: error: unterminated #ifndef
 #ifndef ZEPHIR_KERNEL_MAIN_H
 ^
make: *** [it.lo] Error 1

**Comment by andresgutierrez** [comment]
This was fixed in the latest commit

**Comment by serg-deep** [comment]
Ty
