### ISSUE TITLE
ZEPHIR_GT_DOUBLE : zephir_greater_double missing

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#839]
A needed function of the ZEPHIR_GT_DOUBLE macro is just missing.
Not declared in a header or in the source.
Probably just not yet implemented.

**Comment by ovr** [comment]
https://github.com/phalcon/zephir/blob/master/ext/kernel/operators.h#L67

**Comment by steffengy** [comment]
This is not fixed, the function "zephir_greater_double" is missing not the macro!
@ovr @andresgutierrez please reopen

**Comment by ovr** [comment]
Oh, Sorry my miss

**Comment by ovr** [comment]
refs https://github.com/phalcon/zephir/pull/861
