### ISSUE TITLE
Zephir cast default argument NULL to expected type, but should not

### ISSUE THREAD

**Issue by coollider** [phalcon/zephir#849]
Example:    
```php
public function testNULLDefault(string! arg0 = NULL, string arg1 = NULL, array! arg2 = NULL, array arg3 = NULL){
  var_dump(arg0);
  var_dump(arg1);
  var_dump(arg2);
  var_dump(arg3);
}
```
Output:
```text
string(0) ""
string(0) ""
array(0) {
}
array(0) {
}
```

Must be:
```text
NULL
NULL
NULL
NULL
```

Generated C code for `arg0`:
```c
	if (!arg0_param) {
		ZEPHIR_INIT_VAR(arg0);
		ZVAL_EMPTY_STRING(arg0);
	} else {
	if (unlikely(Z_TYPE_P(arg0_param) != IS_STRING && Z_TYPE_P(arg0_param) != IS_NULL)) {
		zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'arg0' must be a string") TSRMLS_CC);
		RETURN_MM_NULL();
	}

	if (likely(Z_TYPE_P(arg0_param) == IS_STRING)) {
		zephir_get_strval(arg0, arg0_param);
	} else {
		ZEPHIR_INIT_VAR(arg0);
		ZVAL_EMPTY_STRING(arg0);
	}
	}
```

`arg0` always empty string.

**Comment by phalcon** [comment]
arg0 is defines as string and its type is never changed to other type

**Comment by coollider** [comment]
`arg0 is defines as string and its type is never changed to other type` but how i can detect that `arg0` was NULL, if it always string?

**Comment by andresgutierrez** [comment]
If you want multiples types you need to use `var` instead of `string`

**Comment by coollider** [comment]
I know, but it is error. If i set `arg0 = NULL ` default value NULL, this mean that input argument can be NULL. Or i am wrong?

**Comment by andresgutierrez** [comment]
Variables can only be of the defined type, this ensures type safety, there is no NULL in the string universe of values so an empty string is the most approximate value for it.
