### ISSUE TITLE
Again problem with str_replace array

### ISSUE THREAD

**Issue by valVk** [phalcon/zephir#864]
#381 closed and @phalcon said that was fixed.

But seems like this issue appeared again.

```
var patterns = [
    ":any": "[^/]+",
    ":num": "[0-9]+",
    ":all": ".*"
];
var searches, replaces, str;
let str = "mystringwith:anyinside",
    searches = array_keys(patterns),
    replaces = array_values(patterns);
var_dump(str_replace(searches, replaces, str));
```

result is `NULL`

**Comment by ovr** [comment]
сС @steffengy

**Comment by steffengy** [comment]
@ovr 
any reason why this was CC'ed to me? Can't remember touching anything in that area.
Anways PR referenced above.

**Comment by ovr** [comment]
@steffengy 
At all, you fixed it, good job :+1:

**Comment by steffengy** [comment]
@valVk 
Should be fixed in master now.
Any further problems with str_replace?

**Comment by valVk** [comment]
Hi.

Probably in tame when I got this issue my zephir wasn't up to date. Sorry about that.

Now with Zephir version 0.6.1a everything works fine

The result string after str_replace looks like expected: `string(23) "mystringwith[^/]+inside"`

Thanks.
