### ISSUE TITLE
PDO Memory usage issue (leak/increasing memory usage)

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#868]
Followup of #867 

PHP version:
----
works fine, without increasing memory usage.
```
$connection = new \PDO("mysql:<connection_params>", "user", "pw");
    while (true) {
        $statement = $connection->prepare("SELECT * FROM users");
        $statement->closeCursor();
    }
```

Zephir version:
----
worked fine before optimizations,
results in ``Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 24 bytes)``
```
var statement, connection;
        let connection = new \PDO("mysql:<connection_params>", "user", "pw");
        while 1 {
            let statement = connection->prepare("SELECT * FROM users");
            statement->closeCursor();
        }
```

Connection Params
----
pretty standard:
 ``charset=UTF8;unix_socket=xxx;dbname=xxx``

**Comment by andresgutierrez** [comment]
It seems the problem happens because PDO::prepare returns a reference with refcount=1, can you try again using master?

**Comment by steffengy** [comment]
seems to be fixed, thanks :)
