### ISSUE TITLE
__call, RuntimeException: call to undefined method

### ISSUE THREAD

**Issue by mruz** [phalcon/zephir#874]
Hi, 
I have magic call in the Di:
```zep
public function __call(string! method, arguments = null)
    {
        var service, value;

        // If the magic method starts with "get" we try to get a service with that name
        if starts_with(method, "get") {
        //if strpos(method, "get") !== false {
            let service = lcfirst(substr(method, 3));

            if this->has(service) {
                fetch value, arguments[0];
                return this->get(service, value);
            } else {
                throw new Exception(sprintf("The '%s' service is required", service));
            }
        }

        // If the magic method starts with "set" we try to set a service using that name
        if starts_with(method, "set") {
            fetch value, arguments[0];
            this->set(lcfirst(substr(method, 3)), value);
            return null;
        }

        // The method doesn't start with set/get throw an exception
        throw new Exception("Call to undefined method or service '" . method . "'");
    }
```
If I run in the zephir world:
```zep
let request = this->_di->{"getRequest"}();
```

with the latest changes I reveive:
> RuntimeException[0]: Call to undefined method Ice\Di::getrequest()

But there is a request service. https://github.com/phalcon/zephir/commit/acfbbd059b2f653bb88c48763b65485b5dc75b54#commitcomment-10572145

**Comment by andresgutierrez** [comment]
I've added tests for calling __call magic methods in:

https://github.com/phalcon/zephir/blob/master/test/mcalldynamic.zep
https://github.com/phalcon/zephir/blob/master/unit-tests/Extension/MCallDynamicTest.php

They're passing:
https://travis-ci.org/phalcon/zephir/builds/57385594

**Comment by mruz** [comment]
Could you try to run [ice/framework](https://github.com/ice/framework) and [ice/hello](https://github.com/ice/hello)?

**Comment by mruz** [comment]
I did back to https://github.com/phalcon/zephir/commit/9ba79125bc59f65aedd40f840b33a5a4b3ff8af8, so update composer.json before run `zephir build` please:
```
"phalcon/zephir": "dev-master"
```

**Comment by mruz** [comment]
Thanks.
