### ISSUE TITLE
Where CompiledExpression.php ?

### ISSUE THREAD

**Issue by wskdf** [phalcon/zephir#876]
```$ zephir generate```

PHP Warning:  require(/opt/zephir/Library/Optimizers/FunctionCall/CompiledExpression.php): failed to open stream: No such file or directory in /opt/zephir/Library/Loader.php on line 48
PHP Fatal error:  require(): Failed opening required '/opt/zephir/Library/Optimizers/FunctionCall/CompiledExpression.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/zephir/Library/Loader.php on line 48

**Comment by andresgutierrez** [comment]
Did you install the dependencies?

```php
composer install
```

**Comment by wskdf** [comment]
Recently installed. But still get error

PHP Fatal error:  Class 'Zephir\Optimizers\FunctionCall\CompiledExpression' not found in /home/wskdf/coba/optimizers/TahedeTesOptimizer.php on line 32

```
return new CompiledExpression("double", "my_tahede_tes(" . $resolvedParams[0] . ")", $expression);
```

The code from zephir manual, I only replace function name.

**Comment by andresgutierrez** [comment]
You have to add at the beginning of the file /home/wskdf/coba/optimizers/TahedeTesOptimizer.php:

```php
use Zephir\CompiledExpression;
```

**Comment by wskdf** [comment]
Generate and compile success, but extension not work

/usr/sbin/apache2: symbol lookup error: /usr/lib/php5/20090626/coba.so: undefined symbol: my_tahede_tes

I'm not must use "my_calculate_pi" right?

**Comment by andresgutierrez** [comment]
You have to add the C source file where my_tahede_tes is implemented to your project, like this: https://github.com/phalcon/cphalcon/blob/2.0.0/config.json#L23-L34

**Comment by wskdf** [comment]
I did.
But solved now. Run ``` zephir fullclean``` and generate again,,,,
Thank's
