### ISSUE TITLE
Add `goto` and `label` to zephir.

### ISSUE THREAD

**Issue by coollider** [phalcon/zephir#879]
I want create parser generator. All fast parser generators use `goto` statemnts for speed. Can you add it to zephir?

**Comment by ovr** [comment]
:-1: 
Use c language layer for parser(s) and optimizer(s) to work with it

**Comment by golovanov** [comment]
-1

**Comment by Green-Cat** [comment]
:-1:

**Comment by nkt** [comment]
Generated code should be compiled, Zephir not supports runtime (for now). So you can output
```zep
%{goto foo;}%
```
And this code will be compiled successfully.

**Comment by coollider** [comment]
@nkt ty. I think it can solve my problem.
