### ISSUE TITLE
Need downgrade zephir

### ISSUE THREAD

**Issue by wskdf** [phalcon/zephir#883]
I just tried to compile my extensions generated by zephir 0.6.1a in Windows, and I get error.
When still use version 0.5.9a and 0.6.0a, everything is fine. But I've deleted my code generated with version 0.6.0a, so can't paste here.

```
basefs.zep.c(93) : error C2198: 'zephir_floor' : too few argu
ments for call
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0
\VC\BIN\cl.exe"' : return code '0x2'
Stop.
```

Generate with 0.5.9a

```
zephir_array_fast_append(prefix, _0);
ZEPHIR_SINIT_VAR(_1);
ZVAL_DOUBLE(&_1, zephir_safe_div_long_long(((zephir_fast_strlen_ev(size) - 1)), 3 TSRMLS_CC));
ZEPHIR_CALL_FUNCTION(&factor, "floor", &_2, &_1);
zephir_check_call_status();
ZEPHIR_SINIT_NVAR(_1);
ZVAL_LONG(&_1, 1000);
ZEPHIR_CALL_FUNCTION(&_3, "pow", &_4, &_1, factor);
zephir_check_call_status();
ZEPHIR_SINIT_NVAR(_1);
div_function(&_1, size, _3 TSRMLS_CC);
```

Generate with 0.6.1a
```
zephir_array_fast_append(prefix, _0);
ZEPHIR_INIT_VAR(factor);
ZEPHIR_SINIT_VAR(_1);
ZVAL_DOUBLE(&_1, zephir_safe_div_long_long(((zephir_fast_strlen_ev(size) - 1)), 3 TSRMLS_CC));
zephir_floor(factor, &_1);  <<------------------ This is Line 93
ZEPHIR_INIT_NVAR(_0);
ZEPHIR_SINIT_VAR(_2);
ZVAL_LONG(&_2, 1000);
zephir_pow_function(_0, &_2, factor);
ZEPHIR_SINIT_VAR(_3);
div_function(&_3, size, _0 TSRMLS_CC);
```

So, how to downgrade to version 0.6.0a ?

**Comment by Green-Cat** [comment]
0.6.0 is tagged (https://github.com/phalcon/zephir/tree/0.6.0), so you can just revert to it using git, then run ./install again.
But I think it would be much better to identify and solve the bug instead.

**Comment by andresgutierrez** [comment]
You need 0.6.1 as it's generating the missing parameter TSRMLS_CC your compiler is asking for:

* https://github.com/phalcon/zephir/blob/3d91448b188b49d1354e8843d86c2c716cc2e334/ext/kernel/operators.h#L169
* https://github.com/phalcon/zephir/blob/b54c88832a60b593f9cdfdeb2d34f36af0bf3169/Library/Optimizers/FunctionCall/FloorOptimizer.php#L70
* https://github.com/phalcon/zephir/blob/959818a694b1cbe1ecf0e01f09375ca179efab80/ext/kernel/operators.c#L896

**Comment by wskdf** [comment]
When I compile in Linux is fine, but in Windows is not.

This is my basefs.zep. 

```PHP
namespace Tumbihe\Fs;

abstract class BaseFs
{
	protected _last_error;

	protected function _calc_size(var size, boolean! _string=TRUE) -> double|string
	{
		var prefix, factor;

		if _string === TRUE {

			if size < 0 {
				return "NaN";
			}
			
			//http://jeffreysambells.com/2012/10/25/human-readable-filesize-php
			let prefix = ["B","kB","MB","GB","TB","PB","EB","ZB","YB"],
				factor = floor((strlen(size) - 1) / 3);

			return sprintf("%.1f", size / pow(1000, factor)) . " " . prefix[factor];

		}

		return size;
	}
}
```

there are to be improved?

**Comment by andresgutierrez** [comment]
Are you copying the files in ext/kernel/ ?

**Comment by wskdf** [comment]
Yup
Entire ext folder. after run ```zephir fullclean````

**Comment by steffengy** [comment]
latest master works fine for me on win32, generating the proper code.

**Comment by wskdf** [comment]
Generate with version 0.6.2a. 
Work fine on windows now.... (y)
