### ISSUE TITLE
Closure issue [$25]

### ISSUE THREAD

**Issue by wskdf** [phalcon/zephir#888]
Zephir\ParseException: Syntax error in *******.zep on line 10

```
  let result = array_filter(array_keys(all_list), function(item) use (only_list) {
-------------------------------------------------------------------^

**Comment by Green-Cat** [comment]
Zephir does not support use() for closures.
As a work around you can put the parameters in an array and use call_user_func_array.

**Comment by KonstantinKuklin** [comment]
@Green-Cat Do you plan to support generators and coroutines?

**Comment by valVk** [comment]
how could we convert that syntax to the correct one?

Thanks.

**Comment by baszczewski** [comment]
**Use** keyword is **extremely useful**. It allow us to inherit variables from the parent scope. Is there any plans to support it?

**Comment by fezfez** [comment]
Any news ?

**Comment by kristoftorfs** [comment]
Is there any news on this issue yet? I'm currently doing a rather large project in Phalcon, but would like to use Zephir instead of PHP for development. However, this is kind of a major issue (for me personally).

**Comment by dkeepersun** [comment]
yeah ,its really useful  .  so many closure i use in my project.  its will be very important feature!

**Comment by kse300489** [comment]
Right now it can't be added to zephir, becouse anonimus functions in zephir it is not `Closure` like in php, it is simple function name. When you write in zephir:

``` php
return array_map(function(var item){ return item + 1; }, value);
```

Zephir simple create new function with unredable name, like: 

``` php
function func_101193d7181cc88340ae5b2b17bba8a1(var item) {
  return item + 1;
}
```

and then use it like this

``` php
return array_map('func_101193d7181cc88340ae5b2b17bba8a1', value);
```

So anonimus functions in zephir it simple named functions.

**Comment by Jurigag** [comment]
Could this be somehow implemented @sjinks ? Lately i added factories to phalcon so for example we can do something like:

```php
use Phalcon\Db\Adapter\Pdo\Factory;

$config = new Phalcon\Config\Ini('config.ini');
$di->setShared('db', Factory::load($config->database));
```

But obviously on this point it will create database adapter object, i just wonder if this could be implemented so i could add some method like `loadAsCallback` which will simply be:

```
public static function loadAsClosure(options) 
{
    return function() use (options) {
        return Factory::load(options);
    }
}
```

Or there is some other workaround for this? Is something like this gonna work:

```
public static function loadAsClosure(options) 
{
    var f;
    
    let this->options = options;

    let f = function() {
        return Factory::load(this->options);
    }

    f->bindTo(this);

    return f;
}
```

?

Well already can tell it won't work.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/zephir/issues/642

**Comment by kran** [comment]
use `bindTo` to solve this: 
```zep
var dummy;
let dummy = new \stdClass();
let dummy->foo = "some variable";

(function(){
    var dummy = <\stdClass> this;
    echo dummy->foo;
})->bindTo(dummy);
```

**Comment by sergeyklay** [comment]
Should work in current development branch. Thank you for the contributing, and for helping us make Zephir better. Feel free to open a new in case of any issue.
