### ISSUE TITLE
Static property access causes read-only (not tracked) temp variables to be observed

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#894]
I experience property fetching randomly failing (this_ptr corrupted or something?)
If that's the case zephir_read_property or fetch_property_this results in an invalid zval,
that has nothing to do with the actual value of the actual property. 
(IS_ARRAY insteadof IS_LONG - eventually rarely something completely uninitialized)

This is all resolved by commeting the new 50600 function call optimization ifdefs:
State: Investigating...

* Bug caused by: zephir_fcall_method/ZEPHIR_FCALL_TYPE_ZVAL_METHOD *
* Disappears when doing the following in **zephir_call_class_method_aparams**:
```
case zephir_fcall_method:
    default:
        assert(object != NULL);
      + Z_ADDREF_P(object);
``` 
(but results in a memleak in another case)

**Comment by steffengy** [comment]
@andresgutierrez 
Any idea what might be wrong there?

**Comment by andresgutierrez** [comment]
Could you please post the code that shows the problem?

**Comment by steffengy** [comment]
@andresgutierrez 
Still working on producing a small testcase, the current code base is rather complex,
which is a part of a reason, why I don't exactly know what's causing this behavior.

**Comment by steffengy** [comment]
@andresgutierrez 
Can you take a look at this?
So I think I was able to track down the cause of the bug:

It seems like it happens when **return_value = object_ptr** on a method call:
In some cases it's possible that because of **OBSERVE_OR_NULLIFY_ZVAL**
an object_ptr is destroyed during a method call. (That's why adding a reference fixes it)
This probably leads to the strange bugs I discovered before (since the object "gets broken")

The codebase I used locally fails because of Z_OBJCE_P (in ZEPHIR_CALL_METHOD) using a garbage-collected zval,
which is very likely related to this.

**Some example code which illustrates the issue**
(I'm not entirely sure this is the same bug, but it atleast is very similar to what I'm experiencing locally -> There could be more bugs)

```
class AADebug
{
    public static function run()
    {
        var g;
        let g = new AADebug();
        let g = g->a();
        var_dump(g);
    }

    public function a() -> <AADebug>
    {
        return this;
    }
}
```

PHP: ``return AADebug::run();``

**Comment by steffengy** [comment]
Atleast my local case (not the example code) works 
when disabling fcache or reverting changes to before
0d420b55c3c4f00a82967b99c9536488e195e973 (which may just be luck)

**Comment by andresgutierrez** [comment]
Can you try again using the latest commit in master?

**Comment by steffengy** [comment]
My example code works now, but it seems like that's not all to it,
since my local code still fails.
Seems like I will have to try harder, but this bug is really confusing so far.
I don't really see how disabling function cache prevents the zval from being
garbage collected in one case...

**Comment by steffengy** [comment]
@andresgutierrez 
Finally managed to produce a low/medium sized test-case... (That bug is still confusing)
See steffengy/zephir_crash_sample
