### ISSUE TITLE
add typeof param === "closure"

### ISSUE THREAD

**Issue by akaNightmare** [phalcon/zephir#898]

**Comment by KorsaR-ZN** [comment]
@akaNightmare You can emulate this with is_callable()

**Comment by andresgutierrez** [comment]
or: 

```php
public function something(<\Closure> hello)
```

**Comment by akaNightmare** [comment]
@akaNightmare, I know i can, but closure it's PHP type too, and would be better implement it to zephir

**Comment by andresgutierrez** [comment]
A closure is not a type, it's a class:

* http://php.net/manual/en/language.types.php
* http://php.net/manual/en/class.closure.php

**Comment by akaNightmare** [comment]
my fail)
