### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by nkt** [phalcon/zephir#913]
I've started develop `zephir-ide`, plugin for Atom. Firstly I wrote a script for collecting function signatures.
Stubs for json: https://github.com/nkt/zephir-ide/blob/master/stubs/functions/json.json
This stubs are better than reflection because they contain args types. Using it in zephir we could improve compile-time static analysis with messages like:
```
json_decode(value, 1);
-------------------^
json_decode 2 argument should be boolean 
```

**Comment by sergeyklay** [comment]
> I've started develop zephir-ide, plugin for Atom.

Wow :+1:
