### ISSUE TITLE
Operator Empty throws "notice"

### ISSUE THREAD

**Issue by KorsaR-ZN** [phalcon/zephir#917]
In code:
```
if !empty definition["limit"] {
....
```

In PHP:
```
Notice: Undefined index: limit in test2.php on line 26
```

**Comment by andresgutierrez** [comment]
'empty' does not work as in php, maybe you want to use 'isset'?

**Comment by KorsaR-ZN** [comment]
@andresgutierrez 
Only such a solution?
```
if isset definition["limit"] && !empty definition["limit"] {
.... expr if the key exists and is not empty ....
}
```

**Comment by colorvamp** [comment]
I think this sould be documented here: https://docs.zephir-lang.com/0.12/en/operators#empty
Because there is absolutely nothing in the "empty" documentation that suggest this different behaviour.
