### ISSUE TITLE
Mixing tabs with spaces in stub files

### ISSUE THREAD

**Issue by ufocoder** [phalcon/zephir#922]
there's mixing spaces and tabs in stub files after command execution:
```bash
zerhir build
```
There're spaces before PHPDoc for class method and one tab before class method signature

For example:
![2015-04-26 18 20 21](https://cloud.githubusercontent.com/assets/2094547/7337167/941cb9bc-ec38-11e4-98db-f9da1fb1b8ee.png)

**Comment by SidRoberts** [comment]
Hopefully #899 should have fixed this. Can you try again with the latest commit on master?

**Comment by ovr** [comment]
Seems to be closed
