### ISSUE TITLE
Mixed type for return value

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir#937]
Is there any chance add to Zephir `mixed` return type?

Example:

```zephir
public function foo() -> mixed
{
   ...
}
```

It would be convenient for a better generation of docs/stubs and support for IDE.
Thanks

**Comment by andresgutierrez** [comment]
mixed is not a type, maybe use `var`?

**Comment by sergeyklay** [comment]
Thanks

**Comment by sergeyklay** [comment]
Open because `var` is not implemented in Zephir yet

**Comment by mruz** [comment]
How about to specify the types?
```zep
public function foo() -> int | boolean
{
   ...
}
```

**Comment by sergeyklay** [comment]
@mruz :+1:

**Comment by sergeyklay** [comment]
Close  because `var` is already implemented in Zephir
