### ISSUE TITLE
Standart loop for

### ISSUE THREAD

**Issue by valVk** [phalcon/zephir#940]
```php
		for (i = 0; i < length; i += limit) {
			let r[] = mb_substr(value, i, limit, charset);
		}
```

Zephir\ParseException: Syntax error in /freespace/sites/phalcon/zephir-projects/twigz/twigz/functional.zep on line 492

	  for (i = 0; i < length; i += limit) {
	------^

How can I use this syntax in scope of zephir?

Thanks.

**Comment by steffengy** [comment]
Duplicate of #741

**Comment by valVk** [comment]
Thanks for pointing
