### ISSUE TITLE
Building on windows fails without any help

### ISSUE THREAD

**Issue by wapmorgan** [phalcon/zephir#950]
Hi. I can not compile extension on windows. All path variables configured properly.

But `zephir build` fails with:

```
Zephir\Exception: Cannot parse file: C:\Users\...\Documents\ZephirTranslator\
...\...\....zep
```

What else can I check?
##

**Comment by steffengy** [comment]
It seems like this is parser related.
(The windows parser binary is still outdated)

You can try to grab the latest one from appveyor and replace bin/zephir-parser.exe with it,
and it should most likely work (if it does under linux)

Another possibility could be that you previously aborted a build, which requires a fullclean 
(deleting the .temp folder should be the important part here)

**Comment by wapmorgan** [comment]
Have downloaded latest zephir-parser.exe and replaced original one.
Manually removed .temp dir.

`fullclean` command says "system can't found that path" three times.

Result of `build` didn't change.

**Comment by steffengy** [comment]
fullclean is not implemented on win32 yet.
A fullclean should be something like:
- Delete .temp (which you did)
- Delete **all files** in ext/
- Delete the folder named after your extension in **ext** (e.g. ext/test)

Also is this really a win32 problem (does it work using the linux version?)
Could you share the code producing that crash?
If not, could you share a sample which triggers the same crash?

**Comment by hylent** [comment]
Why don't you generate c code on Linux, then compile it on Windows?

**Comment by wapmorgan** [comment]
steffengy, Yes, it is Windows-related.

Example code that does not work under win, but does under linux.
https://github.com/php-fa/zephir-test

On linux:
``` sh
git clone https://github.com/php-fa/zephir-test wapmorgan
zephir init wapmorgan
cd wapmorgan
zephir compile
```
And result is
```
Preparing for PHP compilation ...
...
```

Under windows:

``` sh
git clone https://github.com/php-fa/zephir-test wapmorgan
zephir init wapmorgan
cd wapmorgan
zephir compile
```
And output is
```
Zephir\Exception: Cannot parse file: C:\Users\...\Documents\wapmorgan\wapmorg
an\zephirtranslator\FileSearcher.zep
```

**Comment by steffengy** [comment]
I do not get such error, it compiles perfectly for me.
