### ISSUE TITLE
Superglobals in operators are not branched properly

### ISSUE THREAD

**Issue by steffengy** [phalcon/zephir#951]
Zephir:
```zep
if isset _GET["test"] && isset _POST["test"] {
    echo "a";
}

if isset _POST["test"] {
  
}
```
This leads to a hard crash, when _GET["test"] is not set.

Generated Code:
```c
zend_bool _0;
zval *_GET, *_POST;

zephir_get_global(&_GET, SS("_GET") TSRMLS_CC);
_0 = zephir_array_isset_string(_GET, SS("test"));
if (_0) {
    zephir_get_global(&_POST, SS("_POST") TSRMLS_CC);
     _0 = zephir_array_isset_string(_POST, SS("test"));
}
if (_0) {
      php_printf("%s", "a");
}
if (zephir_array_isset_string(_POST, SS("test"))) {
}
```

The problem here is that the (logical) **AND** operator is not
creating a separate branch (aswell as other operators), 
leading to **_GET** being initialized at the **ROOT** branch.
Therefore when accessing it (at the second if), the global is not fetched 
(which it should).

**Comment by steffengy** [comment]
Workaround referenced above, currently no real idea how to fix it properly,
since you either have to do it as in the workaround or you have to track expressions and
branches/conditions where it already has been set...

@andresgutierrez Any idea?

**Comment by steffengy** [comment]
@andresgutierrez 
Any idea how to fix this properly?
I only can think of
- Fetch superglobals at the start of the method (making them branch independent)
- The workaround referenced above, which checks if they were already fetched.

I actually prefer the first one, since the proper fix is probably not really easy to implement,
since you would have to modify large parts of operator behavior and somehow track branches/conditional paths where
the superglobal has already fetched or still is/could be unitialized.

**Comment by andresgutierrez** [comment]
@steffengy I think we could fetch super-globals in the branch zero, so they will be available for any branch
