### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by andresgutierrez** [phalcon/zephir#952]
It seems the generation of extensions from PHP5 changes dramatically in PHP7 due to the modifications to internal structures.

As I see it will require:

* A separate kernel specifically focused on PHP7
* A new memory manager designed to address the reference counting changes in PHP7
* A new approach on generating method/function calls
* A new approach on reusing zval variables
* It would be hard to have a common generated code for both PHP5 and PHP7

Also, It seems that the amount of changes is larger than I expected previously and I think these changes will take many hours and it's something we have to address as soon as possible before move forward.

**Comment by andresgutierrez** [comment]
Old issue https://github.com/phalcon/zephir/issues/756

**Comment by steffengy** [comment]
@andresgutierrez 
> A separate kernel specifically focused on PHP7
> A new memory manager designed to address the reference counting changes in PHP7
> A new approach on reusing zval variables
> It would be hard to have a common generated code for both PHP5 and PHP7

Totally agree on this points, as that matches the result of experiments I conducted.

> A new approach on generating method/function calls

This actually has not changed very much, what problem do you see here?

I think another issue will be that currently we have localOnly and "global" (heap) zval's,
which result in different handling on the compiler side (PHP).
Any idea how to implement the different code generation for PHP7?
It seems like it will require huge amounts of changes (and removing some duplicated code)
to achieve that. (And therefore could easily result in a mess with very much if's)

Another interesting example for that is basically the StringsManager, which creates C code for concatenation, which also has to be changed for PHP7 (zend_string, no ``zval **`).

Some examples of kernel functions can be taken from my first/second experiment,
while it should only be used as reference, since some implementations are kept
too simple to not consume all my time by porting that complexity 
(e.g. array multi update in first experiment).

I still think the most important part will be to find a good way to implement the code generation
for PHP5/PHP7 in the compiler, which will require a smart way to solve it, since you basically
can not leave many places untouched...

**Comment by hylent** [comment]
:+1:

**Comment by baszczewski** [comment]
In my opinion you can abandon support to old php version and make more efforts to support PHP 7. Everyone who will use Zephir, probably can install new php version to.

**Comment by steffengy** [comment]
@andresgutierrez 
What do you think about the approach in 12bbcba4a014f90c664498c6ce57a25fe5500c2d

Basically it's a separate bare kernel, which is used when compiling using PHP7, 
with a basic "skeleton" needed to compile an empty extension,
which should allow porting feature by feature.

On the compiler side we can use ``Utils::isNG()`` to check for PHP7.

**Comment by andresgutierrez** [comment]
@steffengy I like your approach, however I think now is the right moment to refactor the compiler to allow more than one output backend so we can generate extensions for php5, php7 and probably generate plain php in the future

**Comment by steffengy** [comment]
@andresgutierrez First Alpha is announced for Jun 11 2015 
https://wiki.php.net/todo/php70#timetable
so what's the further course of action?
Also is there already a plan of what's to be done to support multiple backends?

**Comment by andresgutierrez** [comment]
The main idea is, create a directory called: `Library/Backends`

```
Library/Backends
     ZendEngine2/
       Expressions/
         Operators/
         Statements/
         Backend.php
     ZendEngine3
       Expressions/
         Operators/
         Statements/
         Backend.php
     PHP
       Expressions/
        Operators/
        Statements/
        Backend.php
     ...
```

For the kernel:

```
    kernels/
      ZendEngine2/
            memory.c
            ...
      ZendEngine3/
            memory.c
            ...
```
                    
So, instead of generating the code, we ask a "backend instance to do it":

```php
//Before
$codePrinter->out('ZEPHIR_CPY_WRT(' . $variable1->getName() . ', ' . $variable2->getName() . ');');

//Now
$this->backend->genCopyOnWrite($variable1, $variable2);
```

**Comment by steffengy** [comment]
Is the goal there then to completly abstract code generation to method calls
or will backend code 
(for example ZendEngine2/Statements/LetStatement) still output code directly
(except for stuff that's needed as abstraction like genCopyOnWrite)

I guess the plan is to abstract it completly leading to probably more readable code?
(Easier changes than replacing a string everywhere)
Won't total abstracting of operators/statements generate much "common" (->code duplication) code between the backends?
Or is the plan to have a "root" level of Statements/Operators which only delegate output specifc tasks to the backend, which probably makes more sense (keep the main execution logic, which should be equal for each interface, at a root level)

Also what's the schedule on this?
It seems like a very extensive refactoring operation, which will probably need very much time.
Is this operation already in progress or is this only a plan (or to be planned to be exact) for now?

**Comment by niden** [comment]
Generating plain php from Zephir has been discussed since the early days of Zephir development. I agree with Andres that a refactoring of the compiler will provide tremendous functionality. 

One output will be php5, one 7, one C and who knows what else. ;)

**Comment by dreamsxin** [comment]
@niden +1
According to different output types, choose different generation engine, it can meet the demand of the current and future development.

**Comment by steffengy** [comment]
I also agree that refactoring the compiler generally is very much needed.
(not only in that regard)

With the first alpha of PHP 7 released, this is still something that should
be started as soon as possible, requiring a clear plan for implementation.

Currently it seems like this is in a kind of "postponed" state, which
also delays the actual PHP7 support in a near future.

**Comment by steffengy** [comment]
@andresgutierrez 
What do you think of 6eb1503e5b6f460a33b44eee75a2fdbcb82d0709 ?

Changes include:
- Template/Kernel files dependant on backend
- Active backend detection (PHP5->ZE2,PHP7->ZE3), 
<br>if no backend is specified via ``--backend ZendEngine2`` for example
- Bare kernel for ZE3 and basic templates

**Comment by hylent** [comment]
Will `zephir generate` generates separate `ext` folders for both PHP5 and PHP7?

**Comment by steffengy** [comment]
@hylent 
In that draft it will generate the ext folder according to the active backend.
So if you decide to compile for PHP7 you would logically get that kernel as output.

Anything else also does not make very much sense since the generated
code will anyways not be very compatible with other kernels.

**Comment by andresgutierrez** [comment]
@steffengy Yes, this is the idea I have, would you mind submit a PR?

**Comment by swen100** [comment]
:+1:

**Comment by finchcn** [comment]
I used zephir to build phalcon with php7, zend_uint and zval_object_value are not supported now, please change they to zend_ulong and zval_object.

**Comment by steffengy** [comment]
@finchcn 
What are you talking about?
zend_uint is bc'ed ages ago due to 2750ecb3bcc090f13373e0d1965af88b9fd438dd (main.h)
zval_object_value is not even used anywhere.

The issues you mention have nothing to do with this PR and probably
are due to phalcon's C components, which also have to be updated,
to compile it for PHP7.

**Comment by finchcn** [comment]
@steffengy 
zen_uint is used in zephir/kernels/ZendEngine3/globals.h line 61.
zend_object_value is used in zephir/Library/ClassDefinition.php

**Comment by steffengy** [comment]
@finchcn 
Sorry but you are looking at regular zephir sources and mentioning old issues
here and frankly wasting my time, since you probably haven't even looked at PR's?

zend_uint is defined by zephir, so it's **no problem**, as mentioned above.
zend_object_value is **not used in ClassDefinition**, where you probably
have not checked my PR or since recently the development branch but the current zephir sources (master).
( https://github.com/phalcon/zephir/blob/development/Library/ClassDefinition.php )

Please do not mention old issues multiple times.

**Comment by GreenRover** [comment]
Hello, is there any progress for PHP7 support in zephir?
Any beta or stuff that can be tested?

**Comment by steffengy** [comment]
There is initial support available. Might work fine for your project or not at all

**Comment by ghost** [comment]
Which branch is the initial support in?

**Comment by steffengy** [comment]
It's available in master.

**Comment by ghost** [comment]
Great. How would one compile the extension when using 7? Are there any options to set?

**Comment by steffengy** [comment]
If you're using PHP7 to run zephir, it should work with the same steps as for PHP5.
If not you have to specify the backend manually, as described in the related PR.

**Comment by ghost** [comment]
After running generate and build under Zephir, the compilation fails. Where do I specify a backend?

**Comment by steffengy** [comment]
`zephir generate --backend ZendEngine3` or `zephir build --backend ZendEngine3`
It's just another argument.

Be aware that zephir has to find PHP7 for build to work (since installing/building against PHP5 with a PHP7 extension can't work)

**Comment by Izopi4a** [comment]
```
zephir build --backend ZendEngine3
```

gives me

```
Exception: Unrecognized action "ZendEngine3"

```

**Comment by steffengy** [comment]
zephir build --backend ZendEngine3 works fine for me.
`zephir build --backend=ZendEngine3` might solve the issue, but shouldn't be necessary.
Or just running it using a PHP7 is generally the best option to go, since it makes that argument
not necessary.

**Comment by Izopi4a** [comment]
```
=
```

makes a difference. I wanted to check if phalcon will build, but unfortunatly it does not.
I install my PHPs seperatly, but i can easily hack `php` and `phpize` to point to php7 directory.

Or at least this is what i saw in zephir/Compiler.php.

But anyways, enough spam, I hope you can make phalcon run on php7 soon ( seems to me its out of my league to help you out.. :( )

**Comment by steffengy** [comment]
It's impossible that phalcon will build without modifications, since it uses C-code (for some stuff).

**Comment by Izopi4a** [comment]
Andres seems very busy lately, hopefully he is on it. 
I see a lot of packages across the web, almost ready with it. Waiting for salary to donate again to phalcon :D ( if it makes any difference )

**Comment by Izopi4a** [comment]
I am very sorry for the spam, but because i am super exited, and constantly checking Phalcon repository  for commits about php 7, do you think you can say a very rough date, @andresgutierrez ?

**Comment by andresgutierrez** [comment]
@Izopi4a  I think the progress of Phalcon + PHP7 must be followed in the Phalcon repository. There are couple of C sections that must be migrated to PHP7.

**Comment by Izopi4a** [comment]
yes, i have this [https://github.com/phalcon/cphalcon/branches] on bookmark and i am checking it like 20 times per day :-). I was just curious if you can just say a very rough estimation. Unfortunately i suck with C, but maybe you can tell if you need any help with some parts, and I will do my best to help you out.

**Comment by Jurigag** [comment]
Well PHP7 finally realased, i hope you will work now more on Zephir and phalcon to be avilable on php7 too :).

**Comment by steffengy** [comment]
zephir atleast works for some cases with PHP7.
closing this now, since this is anyways not used anymore to track any issues.

If you experience anything which doesn't work for PHP7, please open a separate issue.

**Comment by DaveM2011** [comment]
Wow i was so close to PHP7.0.3 support got it compiling just fine it installed the module but when i restarted php7.0-fpm it just hung with the module enabled and chewed up 100% cpu but it didnt log anything in any of my logs even the syslogs so i had no idea what was going on it only took 3 file edits :) but i suppose i can update at a later date :( i would love to hear from anyone who has managed to get it working i could get the error log if anyone needs it

**Comment by ifehrim** [comment]
./kernel/main.h:117:3: note: in expansion of macro ‘INIT_PZVAL_COPY’
   INIT_PZVAL_COPY(new_zv, *z);
   ^
Installing...
Internal extension compilation failed. Check compile-errors.log for more information
i try php5.6 version of zephir build  but sitil problem

**Comment by ifehrim** [comment]
i try php7.0 version of zephir build is success
