### ISSUE TITLE
Build failed by "Zephir\Exception: Cannot parse file: ..."

### ISSUE THREAD

**Issue by AlloVince** [phalcon/zephir#974]
Hi guys

Here is my test zephir project:

https://github.com/AlloVince/zephir-test

I am using the master branch of zephir:

```
# zephir version
# 0.6.3a
```
When build this project by run `zephir build`, an error happened as

```
Zephir\Exception: Cannot parse file: /Users/allovince/opt/htdocs/zephir-test/symfony/component/process/pipes/unixpipes.zep
```

But nothing more description, I've no idea which line to fix, is it possible to know the error details?

Best

**Comment by andresgutierrez** [comment]
It's because of the @ https://github.com/AlloVince/zephir-test/blob/master/symfony/component/process/pipes/unixpipes.zep#L121

**Comment by AlloVince** [comment]
Thank you.  it will be better if the compiler could tell which line has problem :)
