### ISSUE TITLE
Question : Is there a standard way to get the current project path

### ISSUE THREAD

**Issue by gsouf** [phalcon/zephir#976]
Right now we can get the the path to the zephir bin thanks to the constant ``ZEPHIRPATH``.

Is there currently a standard way to get the path to the current project where we run the zephir command ?

**Comment by andresgutierrez** [comment]
getpwd() should give you the current path

**Comment by gsouf** [comment]
Thanks @phalcon, do you mean ``getcwd()`` instead ? 
I'm on the purpose to add a standard way to access it, maybe on the future it can be helpful and will avoid a whole refactoring, what's your though about that ?

**Comment by andresgutierrez** [comment]
Yes, it must be getcwd
