### ISSUE TITLE
how to get config from php.ini?

### ISSUE THREAD

**Issue by shanghaiyangming** [phalcon/zephir#982]
How to get config from php.ini?

like this 

my_setting.a = "tcp://127.0.0.1"

**Comment by steffengy** [comment]
should work just as in PHP: http://php.net/manual/de/function.ini-get.php

**Comment by shanghaiyangming** [comment]
i do this things, but it not work
let this->_expire = ini_get("max_execution_time"); // it's ok
let config = ini_get("my.utils.lock.memcached");// it's bad

**Comment by andresgutierrez** [comment]
Implemented in #985
