### ISSUE TITLE
Please add Scrutinizer CI

### ISSUE THREAD

**Issue by ovr** [phalcon/zephir#995]
Hi

@andresgutierrez 
It's the best way to check code quality to protect untracked errors/notices

https://scrutinizer-ci.com/g/new

Thanks

**Comment by ovr** [comment]
ping @andresgutierrez

**Comment by andresgutierrez** [comment]
@ovr What do I have to do?

**Comment by ovr** [comment]
@andresgutierrez 
Login in https://scrutinizer-ci.com/ and add project from github phalcon/zephir
- check php project
- disable phpunit tests on it

Next add budget to the project to see project's metrics

**Comment by andresgutierrez** [comment]
@ovr It's added, what do you mean by "budget"?

**Comment by sergeyklay** [comment]
@andresgutierrez it seems badge :smile_cat:

**Comment by ovr** [comment]
@andresgutierrez 
Badge*

For example
[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/ovr/phpsa/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/ovr/phpsa/?branch=master)

**Comment by ovr** [comment]
ping @andresgutierrez
